### ISSUE TITLE
Synfig looking for a drive

### ISSUE THREAD

**Issue by hughw213** [synfig/synfig#539] opened 2018-05-03 13:37 UTC
[error loading  files-2018-05-03_142351.pdf](https://github.com/synfig/synfig/files/1971047/error.loading.files-2018-05-03_142351.pdf)
**Synfig version & platform**: Synfig studio 1.2 windows7
(we're more likely to help if you're using latest development builds)

**Issue description**:
seems to be preconfigured to a non existant drive. It will eventually open  saved file
from a real disk on the system (bit slow finding the folders)

**Comment by ice0** [comment] 2018-05-04 05:43
Hi! Can you check this with latest development version? https://dev.icystar.com/downloads/SynfigStudio-1.3.6-testing-18.04.22-win64-c71d0.exe

**Comment by morevnaproject** [comment] 2018-05-13 02:45
Possibly duplicate of #489

**Comment by morevnaproject** [comment] 2019-02-14 14:35
Solved in c34cc22.

**Closed by morevnaproject** 2019-02-14 14:35 UTC
