### ISSUE TITLE
[CMake] Incomplete info on About dialog box

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#1730] opened 2020-10-02 07:57 UTC
**Synfig version & platform**:
Building from source
Debian sid

**Issue description**:
1. Missing **Development version**
2. Unknown Synfig version
![Autotools and CMake comparison](https://user-images.githubusercontent.com/24214509/94900222-44ce6980-04b2-11eb-9009-03f4751dc367.png)

I don't know where & how Autotools parses information from but I think CMake is reading it directly from the macro header defined in the source file itself.
https://github.com/synfig/synfig/blob/fa78a4df4f991b039cfe67c6530c377a8713db6b/synfig-studio/src/gui/dialogs/about.cpp#L60-L67

**Comment by rahmanuh** [comment] 2020-10-07 06:41
Hi again, this issue is interesting. May I work on this?

**Comment by Keyikedalube** [comment] 2020-10-07 07:39
If you can understand CMake sure :)

Just check out the code first and if you can determine a fix, then you can request maintainers to assign this issue to you. I haven't figured how to solve this but I'm guessing the cause is from the build generator (CMake).

**Comment by rahmanuh** [comment] 2020-10-07 07:42
Okay. I will study the code first.

**Comment by AYESDIE** [comment] 2020-10-08 11:46
The Development Version part here can be fixed by using [add_definitions](https://cmake.org/cmake/help/v3.0/command/add_definitions.html) where you can pass the git info which is already managed by [cmake/SynfigFindGit.cmake](https://github.com/synfig/synfig/blob/master/cmake/SynfigFindGit.cmake). 

About Synfig Version, it's weird to see it unknown when it's already being set in the beginning, as you can see in this image too. https://github.com/synfig/synfig/blob/fa78a4df4f991b039cfe67c6530c377a8713db6b/synfig-studio/src/gui/dialogs/about.cpp#L82
![image](https://user-images.githubusercontent.com/34449856/95454095-992d8980-0989-11eb-9dc2-8839ba93f669.png)

**Comment by rahmanuh** [comment] 2020-10-09 23:31
I am not sure `set_version(VERSION)` really sets the version, because when I try to see the definition, it points to:
https://github.com/synfig/synfig/blob/fa78a4df4f991b039cfe67c6530c377a8713db6b/synfig-core/src/synfig/layers/layer_mime.cpp#L79
But why it successfully write 1.5.0 below Synfig Studio? :confused:

**Comment by Keyikedalube** [comment] 2020-10-10 01:56
ping @AYESDIE @ice0

**Comment by AYESDIE** [comment] 2020-10-10 05:29
On checking the code, I can see that we are using `Gtk::AboutDialog` as a parent class for our About dialog. So in our case, we are calling `set_version()` from the parent class (which is `Gtk::AboutDialog` here). You can check their documentation over [here](https://developer.gnome.org/gtkmm/3.0/classGtk_1_1AboutDialog.html#a46ba72a65a81ed6e528730de0fc02e29). It works as intended too so there's no issue with that over here.

Tracing the `Unknown` part got me to this file. Using `add_definitions` can help you define `VERSION` which will fix that issue.
https://github.com/synfig/synfig/blob/dfcfdf9fc94953d10562d0fd01d2a83039538068/synfig-core/src/synfig/main.cpp#L114-L122

---

That seems like part of some old code and it can be removed. The `SHOW_EXTRA_INFO` part is managed by this part of the code on that same file.

https://github.com/synfig/synfig/blob/dfcfdf9fc94953d10562d0fd01d2a83039538068/synfig-studio/src/gui/CMakeLists.txt#L22-L25

**Comment by rahmanuh** [comment] 2020-10-11 07:47
Thanks for your hints. The version now is not `Unknown`. I do
`+add_definitions(-DVERSION="${STUDIO_VERSION_MAJOR}.${STUDIO_VERSION_MINOR}.${STUDIO_VERSION_PATCH}")`
in this file 
https://github.com/synfig/synfig/blob/5d0abc1f718ad67469afb0252a9ce42a946cabf3/synfig-core/src/synfig/CMakeLists.txt#L5-L9
![image](https://user-images.githubusercontent.com/22091868/95671904-4b3c9f80-0b9c-11eb-812c-0022113295af.png)

---

Regarding the `DEVEL_VERSION` part, whenever I `add_definition(-DDEVEL_VERSION)` in Line 21, there is error: Segmentation Fault (Core dumped) when I launch SynfigStudio.
```
(synfigstudio:11525): IBUS-WARNING **: 09:47:15.490: Unable to connect to ibus: Could not connect: Connection refused
synfig(11525) [09:47:15] info: Init About Dialog...
Segmentation fault (core dumped)
```

I think it is because of `autorevision.h` not defining `DEVEL_VERSION`. I do not understand why. I suppose it will automatically generated if we `add_definition(-DDEVEL_VERSION)` in [here](https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/CMakeLists.txt)

**Comment by rahmanuh** [comment] 2020-10-11 08:43
[Update]
Finally, I fix it :smiley:
![image](https://user-images.githubusercontent.com/22091868/95674008-b17dee00-0bad-11eb-816b-76b503c833c8.png)

Will make a PR later

**Closed** 2020-10-13 01:32 UTC
Labels: Hacktoberfest
