### ISSUE TITLE
sound plays twice at beginning

### ISSUE THREAD

**Issue by lehtis** [synfig/synfig#424] opened 2017-09-09 18:02 UTC
**Synfig version & platform**: 1.2.0 Win10
(we're more likely to help if you're using latest development builds)

**Issue description**:
Is it my machine, but doing Synfig lipsync tutorial, downloaded from Gumroad.com. When playing with sound, it play beginning of sound twice, no different from which time I play it.

**Comment by morevnaproject** [comment] 2017-09-10 15:01
Confirmed.

**Comment by morevnaproject** [comment] 2017-09-10 15:02
Can you please test if this happens with the latest development version?

**Comment by lehtis** [comment] 2017-09-10 17:30
In 1.3.4 version, yes there is. Little bit different, but same kind of little repeat after beginning.

**Comment by dankamino** [comment] 2017-11-15 11:20
Same problem here!! with beta and stable version the audio repeats and makes it very difficult to animate specially lipsync.

**Comment by techdude** [comment] 2019-02-19 03:38
The issue persists in 1.2.2

**Comment by techdude** [comment] 2019-02-23 21:20
For those waiting for a workaround, the bug doesn't exist on Linux, so you can use that in the meantime.

**Comment by blackwarthog** [comment] 2019-08-04 08:38
It was possibly fixed in latest master (4a5bf0f375545163a306465f37df1f169d40910b). Need to recheck.

**Comment by morevnaproject** [comment] 2019-08-05 12:15
@blackwarthog Confirmed, the issue is fixed. ^__^

Unfortunately, I have noticed another issue appeared - the playback is much slower now (more dropped frames) if any sound layer exists (and enabled) in document. That happens even if document has no graphic layers.

In any case, it's better to have slower playback than "twice-played"/"async" playback that we had before that. ^__^

**Comment by morevnaproject** [comment] 2019-11-08 12:32
> Unfortunately, I have noticed another issue appeared - the playback is much slower now

I have tested again. 

The slow playback happens for this file (its rate is 44100) - 
[sound.wav.zip](https://github.com/synfig/synfig/files/3824550/sound.wav.zip)

The same file converted to 48000 plays smoothly - 
[sound-48000.wav.zip](https://github.com/synfig/synfig/files/3824553/sound-48000.wav.zip)

...but playback gets laggy after timecursor reaches end of file. Does this happens because it tries to read beyond of end of file?

**Comment by morevnaproject** [comment] 2019-11-27 07:05
Removed "Windows" label, as it is affecting Linux too.

**Comment by morevnaproject** [comment] 2019-12-07 15:48
Commit 1f4abf1812809da6b2a61d7702b4f41a81d6920e fixed the issue.

In fact, after building this commit `sound-48000.wav` played perfectly, but `sound.wav` was glitching.

Then I discovered that my system (Linux Mint 19) is missing `libmlt-data` package (problem with Ubuntu dependencies - installing `libmlt` doesn't install `libmlt-data` which is required for libmlt to work properly, as it contains [configuration files](https://packages.ubuntu.com/ru/xenial/all/libmlt-data/filelist) to properly play sounds).

**Closed** 2019-12-07 15:52 UTC
Labels: Critical
