### ISSUE TITLE
[Synfig Studio] Animate button is missing when open sif file exported from Inkscape

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1901] opened 2020-12-07 15:58 UTC
**Issue description**:
https://forums.synfig.org/t/short-cut-for-animate-button/11420

**Comment by rodolforg** [comment] 2021-02-08 01:42
I can't reproduce it.

**Comment by ice0** [comment] 2021-02-09 04:33
@rodolforg I can't reproduce too :(

**Comment by rodolforg** [comment] 2021-02-23 23:23
I looked the code and I couldn't see how it would be hidden.
Even resizing the WorkArea won't make it be hidden (differently of the 'top bar' of workarea).

Asking the post author, [he said he believes it he was using a previous version](https://forums.synfig.org/t/short-cut-for-animate-button/11420/8) .
I think it's safe to close this issue.

**Closed** 2021-02-24 03:59 UTC
