### ISSUE TITLE
Unwanted Vertex Points at the end of line, when using Draw tool 

### ISSUE THREAD

**Issue by THEBATEZIOPARKER** [synfig/synfig#2460] opened 2021-12-13 07:24 UTC
I am using Fedora 35, Synfig-Studio Flatpak version

https://user-images.githubusercontent.com/87817029/145769322-024a5487-443b-4f74-8567-0ede45476a29.mp4

How to Fix This ?

**Comment by ice0** [comment] 2021-12-13 14:02
@morevnaproject @rodolforg 
Any ideas here?

**Comment by rodolforg** [comment] 2021-12-19 19:15
Duplicate of #2448 ?

**Comment by THEBATEZIOPARKER** [comment] 2021-12-20 03:33
@rodolforg Yes

**Closed** 2021-12-26 04:50 UTC
Labels: Duplicate, Regression

**Comment by THEBATEZIOPARKER** [comment] 2021-12-27 15:05
Where Can I Get The Draw Tool Bug Fixed Version ?

**Comment by ice0** [comment] 2021-12-28 05:45
@THEBATEZIOPARKER 
On Linux you can compile it from source.
Flatpak will be available tomorrow.

**Comment by ice0** [comment] 2021-12-29 16:31
@THEBATEZIOPARKER 

Can you check flatpak build?
```
flatpak install --user https://dl.flathub.org/build-repo/70486/org.synfig.SynfigStudio.flatpakref
```

**Comment by THEBATEZIOPARKER** [comment] 2021-12-30 02:29
@ice0 This flatpak build works without any issues
