### ISSUE TITLE
CD/DVD check, error

### ISSUE THREAD

**Issue by mysliwy112** [synfig/synfig#724] opened 2019-02-06 16:50 UTC
**Synfig version & platform**:
Synfig 1.2.2 on Windows 7 64-bit

**Issue description**:
After inserting DVD/CD and removing it.  (In Synfig) Operations like Save, Open (these which lists filesystem) generates a lot of errors (around 5) "There is no disk in the drive. Please insert a disk into drive" it's kinda annoying (and I'am in hard drive directory, not CD one). There are some workarounds, but it would be nice to have it fixed ;)
(But really it's nothing serious, I just letting you know)

**Comment by BobSynfig** [comment] 2019-02-06 18:29
Duplicate of https://github.com/synfig/synfig/issues/489

**Comment by morevnaproject** [comment] 2019-02-07 06:56
@mysliwy112 We made a test build with a fix. Can you please test it? - https://downloads.synfig.org/almost-1.3.11/SynfigStudio-1.3.10-testing-19.02.07-win64-47da2-seterrormode.zip

**Comment by mysliwy112** [comment] 2019-02-07 09:43
Yes, It works now. No errors.

**Comment by morevnaproject** [comment] 2019-02-07 13:20
Awesome! Closing then. ^__^

**Closed** 2019-02-07 15:40 UTC
