### ISSUE TITLE
Cannot rotate or move objects at all.

### ISSUE THREAD

**Issue by FerretMonger** [synfig/synfig#2359] opened 2021-10-12 08:33 UTC
When choosing the rotate tool and trying to rotate (when the mouse changes to a rotate symbol) it either just does a rect selection or scales the shape.

1. Click on any object
2. Select the rotate tool
3. Try to rotate it

(This is true for the move tool as well)

I would excpet the object to rotate.

![image](https://user-images.githubusercontent.com/45817036/136920227-0c3b4735-b9b5-48b6-9799-7aca4b808248.png)
Only draws a rect selection
![image](https://user-images.githubusercontent.com/45817036/136920311-7c7286b2-f3c1-42f4-a346-24f08b2ca79e.png)
Scales the object instead

 - OS: Window
 - OS version: 10 Pro
 - Synfig version: 1.4.2

I've tried boh the stable and development version but the behavior remains the same.

**Comment by yoSachinkr** [comment] 2021-10-12 09:18
It's not a bug. It's basically how few shapes work in synfig.

**Comment by Keyikedalube** [comment] 2022-01-03 17:26
I expected rotate tool to rotate rectangle object too but alas both our expectations went wrong.

Here's how rotate tool works as explained in [Synfig's wiki](https://wiki.synfig.org/Rotate_Tool). The tool's for handle manipulation so it's kinda complex for users used to rotating objects along an angle.

I'm closing this because the wiki already answered how and what rotate tool does. Same for [smooth move tool](https://wiki.synfig.org/Smooth_Move_Tool).

**Closed by Keyikedalube** 2022-01-03 17:26 UTC
