### ISSUE TITLE
Synfig volume parameter not working?

### ISSUE THREAD

**Issue by TROY9109** [synfig/synfig#1045] opened 2019-12-13 21:12 UTC
**Synfig version & platform**:
1.3.11

**Issue description**:

When I change the volume parameter for my audio file it makes no difference to the volume of the audio. The audio volume level stays the same no matter what? Am I doing something wrong? Even when i change it from 1 to 0.015, the volume is still the same. 
I appreciate any help thanks.

**Comment by Jose-Moreno** [comment] 2019-12-14 04:03
@TROY9109 Not sure if it's the same bug but it should have been fixed this week actually. https://github.com/synfig/synfig/commit/1f4abf1812809da6b2a61d7702b4f41a81d6920e

Maybe @morevnaproject can confirm if it's the same issue?

The only problem is that unless you can compile Synfig there's no way to test this for regular users until a new dev build binary is released for all major platforms.

**Comment by morevnaproject** [comment] 2019-12-14 07:31
Yes, this is fixed last week. Issue is duplicate of #388.

**Closed by morevnaproject** 2019-12-14 07:31 UTC
