### ISSUE TITLE
How to enable OpenGL Rendering

### ISSUE THREAD

**Issue by define-private-public** [synfig/synfig#1712] opened 2020-09-28 23:19 UTC
**Synfig version & platform**:
1.3.16 on Ubuntun 18.04 (via AppImage)

**Issue description**:

I was perusing the dev. docs, looking through the parts about the rendering engine: https://synfig-docs-dev.readthedocs.io/en/latest/common/structure.html#render-engine

In there it states there is an OpenGL backend, versus the default enabled one is a software one called Cobra.  Is there a way that I can enable the OpenGL one?  I've found it a bit of a pain how slow it can be to preview my animations.  What I'd love is way to see my edits' results in realtime.  I'm wondering if the OpenGL backend can do this for me.

When I went to change my `WorkArea` render in the `Preferences`, I only saw the software renders available.  Do I need to clone the repo myself and build my own Synfig studio?

**Comment by ice0** [comment] 2020-09-29 03:26
Hi!
As far as I know, the OpenGL renderer is currently disabled because it hasn't finished yet. There are also some effects that are not yet optimized.

For better performance, you can try switching to "draft" rendering and clicking "LowRes" in the upper right corner of the animation window.

I'm also planning to check out for performance issues, so it would be nice if you could share some of the problematic animations, and especially effects that slow down rendering.

**Comment by define-private-public** [comment] 2020-09-29 13:37
On a side note, are there any available stress test animation?  I was poking through the code for the software rendering backend.  I think there are some functions that could be rewritten/reorganized to better take advantage of compiler optimizations.  I'd like to submit a PR on those, but I'd also like to have a test for that stuff too.

**Comment by ice0** [comment] 2020-09-29 14:52
Currently we have quality test to test rendering engine for regressions (https://gitlab.com/synfig/synfig-tests). 
Unfortunately, there are no performance tests yet, but if you know how to implement this, this would be very appreciated.

**Comment by define-private-public** [comment] 2020-09-30 22:30
That seems like it could suffice.  Is there an easy way to perform a render via the command line.  From there, I can use tools like `time` and `perf` to track how long it takes to do a render.

**Comment by ice0** [comment] 2020-10-01 03:21
Yes.
You can use `bin/synfig`, which is a console tool that allows rendering from the command line.
use it like `synfig <input.sif> <output> -t <target_format>` for rendering.

It is better to use the `null` target format so it don't waste time to image format conversion.

**Comment by morevnaproject** [comment] 2020-10-01 09:54
There is also `synfigplayer` console tool, which outputs frames in GUI window and also prints stats into console (stats printed every 10 seconds). THis might be more suitable for benchmarking. ^__^

**Comment by morevnaproject** [comment] 2020-10-01 09:59
About OpenGL rendering - you can specify `--with-opengl` option to configure script of `synfig-core`. But the current code is broken and there is high probability it won't compile.

In addition to that the OpenGL implementation supports only few layers - outlines, regions and images (if I remember correctly).

**Comment by rodolforg** [comment] 2020-10-02 22:53
A while ago I changed the code in order to able to build with OpenGL support. Some shaders were missing too.

I was partially succeeded: it builds. But it renders nothing :P

**Comment by define-private-public** [comment] 2020-10-07 23:05
Forgot to ask:
- For linux, that version of GCC is used for the release builds?
- What version of C++ is being used?  I don't see `CXX_STANDARD` defined in the CMake file

**Comment by ice0** [comment] 2020-10-08 01:40
@define-private-public 
- Usually we trying to support at least Debian old-old-stable. Currently with g++ 5.4.0
- C++11

**Comment by define-private-public** [comment] 2020-10-09 02:15
Is there a flag I can supply to the `synfig` to make it run in a `quiet` mode?

**Comment by ice0** [comment] 2020-10-09 02:39
Yes. You can use `--quiet` for this.
There still warnings (always) but this will be fixed soon.
```
./synfig ./about_icon.sif --quiet
mlt_repository_init: no plugins found in "C:\msys64\home\ice0\projects\test_install2\output\lib\mlt"
synfig(17276) [9:37:04] warning: Cannot open ./synfig_modules.cfg
synfig(17276) [9:37:04] warning: Cannot open C:\msys64\home\ice0/.local/share/synfig/synfig_modules.cfg
```

**Comment by ice0** [comment] 2020-10-09 23:43
Excessive warnings were fixed by this PR (https://github.com/synfig/synfig/pull/1751)

**Comment by Keyikedalube** [comment] 2022-01-03 15:39
Closing this issue because as of now OpenGL support on Synfig comes under either "feature request" or "infrastructure improvement".

Copy-pasted blog post from [Synfig's development news](https://www.synfig.org/2015/05/25/development-news/):
> But what about the future of Synfig itself? Our main focus here is to work on optimization of rendering. The idea is to implement OpenGL-powered rendering engine, which should give a significant speed boost. Everyone want a real-time editing and playback, right? This is what Ivan Mahonin is working on.
>
> This is really a big task involving a lot of internal code re-structurization. You can track his progress by following this branch – https://github.com/blackwarthog/synfig/commits/rendering(you might notice Ivan is mostly up for rare, but bold commits here).
>
> Currently Ivan is finishing reorganization of current render engine, which will allow the OpenGL thing to fit nicely. Unfortunately, the code is still far from being usable, so those changes are not included into the main branch yet.

@ice0 already mentioned this too [here](https://github.com/synfig/synfig/issues/1712#issuecomment-700403348).

**Closed by Keyikedalube** 2022-01-03 15:39 UTC
Labels: reminder
