### ISSUE TITLE
Crash when changing the Text parameter of a Text Layer

### ISSUE THREAD

**Issue by jasonrohrer** [synfig/synfig#287] opened 2016-11-13 09:36 UTC
Version 1.02 on Ubuntu Trusty.

Steps to reproduce:

1. Create a new, blank animation.

2. Use Text Tool to create a new Text layer on the canvas.

3.  Select the new layer in the layer list.

4.  In the Parameters panel, double-click the Text value to edit it.

5.  A dialog box comes up for editing the string.

6. Mousing over either button in the dialog box causes a crash (OK or Cancel buttons).  No mouse press is needed.

7.  Pressing ESC or clicking the (X) to close the dialog box does not cause a crash.

As far as I can tell, there's no way to edit a string without causing a crash (pressing Enter in the dialog box creates a newline in the string---thus, you must click the OK button to save the string, and you can't mouse over it without causing a crash).

**Comment by caryoscelus** [comment] 2016-11-13 09:49
Can't reproduce in current master.

**Comment by jasonrohrer** [comment] 2016-11-13 09:54
Just tried to reproduce in 1.02 on Windows.

I can't even create text at all in Windows.  As soon as I hit OK in the text dialog box the first time, Synfig freezes and needs to be force-quit.

**Comment by caryoscelus** [comment] 2016-11-13 10:02
1.0.2 is outdated. You can try development builds if you don't want to build master yourself.

I'm closing this for now. Feel free to reopen if you still experience crash on modern version.

**Closed by caryoscelus** 2016-11-13 10:02 UTC
Labels: Crash

**Comment by morevnaproject** [comment] 2017-10-25 08:16
@jasonrohrer Please see my comment about freeze here - https://github.com/synfig/synfig/issues/242#issuecomment-339251559
