### ISSUE TITLE
Downlad problem Safari 11.0.2

### ISSUE THREAD

**Issue by spazjesu** [synfig/synfig#500] opened 2018-03-05 12:26 UTC
I have tried for two day to download Synfig stable version on Safari, but I just get sent to an error page where it says Safari cannot open the page because there are too many redirections from the original page.

I had no problem downloading the How to Use synfig videos. 

Is there something else I can do? I have tried searching for it from other places online but it is not working and I feel better downloading from Synfig directly.

Thanks!

**Comment by morevnaproject** [comment] 2018-03-08 16:45
Hello! Thank you for reporting. The problem is fixed now. Please try again. ^__^

**Closed** 2018-03-10 05:22 UTC
