### ISSUE TITLE
Mouse diseapear when docking windows

### ISSUE THREAD

**Issue by Jengall** [synfig/synfig#543] opened 2018-05-09 22:50 UTC
**Synfig version 1.2.1 and 1.3.5 & win10 64b**:

**Issue description**:
when trying to dock windows the mouse diseapear what make the task **REALLY** difficult.

**Comment by morevnaproject** [comment] 2018-10-09 17:16
Duplicate of #374.

**Closed by morevnaproject** 2018-10-09 17:16 UTC
Labels: Duplicate
