### ISSUE TITLE
"speed" parameter does not work for switch layers

### ISSUE THREAD

**Issue by zozorg** [synfig/synfig#1479] opened 2020-06-08 11:39 UTC
**Synfig version & platform**:
linux 1.3.14

**Issue description**:
The "speed" parameter appears to be ignored for switch layers as opposed to group layers

**Comment by FirasH** [comment] 2020-06-13 12:22
Cannot reproduce with current master.
Will check for 1.3.14.

**Comment by FirasH** [comment] 2020-06-13 18:02
Cannot reproduce with 1.3.14 either.

Maybe there are some missing steps?
Do you have a file with this issue?

**Comment by morevnaproject** [comment] 2020-06-14 14:24
Hi @zozorg! The speed parameter affects the speed for child layers of Group (or Switch Group). If you wish to speedup the animation of switching in Switch group, then you need to wrap it into another group and set speed parameter from there.

![screenshot_001](https://user-images.githubusercontent.com/332868/84596007-5cdb9800-ae85-11ea-8830-7b10ad09caa8.png)

**Comment by zozorg** [comment] 2020-06-15 03:15
Indeed that was the issue, thanks!

**Comment by FirasH** [comment] 2020-07-12 11:52
@morevnaproject can we close this report?

**Comment by morevnaproject** [comment] 2020-07-12 14:29
Yes! Thank you! ^__^

**Closed by morevnaproject** 2020-07-12 14:29 UTC
