### ISSUE TITLE
RFE: new release?🤔

### ISSUE THREAD

**Issue by kloczek** [synfig/synfig#3311] opened 2024-01-18 14:21 UTC
https://github.com/synfig/synfig/compare/v1.4.4...master shows +2.4k commits since last release.
Do you have aby plans to make new release soon? 🤔

**Comment by rodolforg** [comment] 2024-01-20 16:26
v1.4.4 is a version from 1.4.x branch, that is labeled as "stable branch" - i.e. we try to do little interventions (bug fixes and minor features) that we curate to not add more bugs or regressions. We avoid to change dependency library versions too.

The master branch is active development. We refactor and cleanup code, add major features and structural changes.
We provide development releases with 'odd number' scheme: 1.5.x numbers.

We intend to make a 1.5.2 release, as 1.5.1 is dated from October of 2021. However, we need to finish some touches (see #3293). Even the future release notes is a weight demand due to long time without any releases from master branch -   but now @Keyikedalube is working on it :)

By the way, what does "RFE" mean? "Request For Enhancement"!?

**Comment by BobSynfig** [comment] 2024-05-20 23:18
1.4.5 has been released, to be closed

**Comment by rodolforg** [comment] 2024-05-21 02:17
We hope we have a new 1.5.2 soon lol

**Comment by pgilfernandez** [comment] 2024-05-23 11:25
> We hope we have a new 1.5.2 soon

why is this not happening? I mean, v1.5.x has been a lot of time in development and it works great, I use it in production... is anything blocking it to become the stable version?

**Comment by rodolforg** [comment] 2024-05-24 10:21
> why is this not happening?

Because preparing a release takes much effort than it seems. Believe or not, even writing the release notes takes time - and 2 years without any release ... well... read the ['draft' Keyikedalube made recently](https://docs.google.com/document/d/18U4grQJRDcb7dfp1hMx9tIpdhVmgFjiq0ruseFZNKwA/edit?usp=sharing) - until February 06 '2024 to help us.

Konstantin was away for a while due some reasons and he's great about this project management, test, packaging and release XD

> is anything blocking it to become the stable version?

While in the development branch, we can 'play' with the code more freely 'without caring' about some compatibilities, for example. We were/are making some internal changes on the core for better code maintenance and (theoretically) less bug prone, like creating some unit/feature tests, cleaning up and moving an old internal library to core, porting more layers to Cobra render engine, filepath handling for better support to non-latin characters specially on MS Windows, etc. These changes can occasionally breaks some stuff and we can only know after being better tested by us and general users - so we cannot call it stable. Regressions are so bad  :(

In addition, we have some known bugs that should be gone before a stable release (or even a development one). Some untested PR that could be merged too.
We tried to list them here: https://github.com/synfig/synfig/issues/3293.

**Comment by pgilfernandez** [comment] 2024-05-31 08:57
@rodolforg thank you very much for explaining it all. It was really helpful to understand the Synfig development milestones.
=)

**Comment by rodolforg** [comment] 2024-05-31 11:37
I don't know if we can call it milestones XD

Anyway, I know it's a bit frustrating the release 'delays'; for me too. I even slowed down a lot my contributions partially due my real-life job, but also to make it easier to release a new dev version. lol

**Comment by pgilfernandez** [comment] 2024-05-31 12:07
Don`t worry, I called milestones as a placeholder, hehehe

I was interested to know this (and probably lot of other users as well) because it looks like 1.5.x branch is kind of an experimental and future version but it has been on the works for more than 2 years... We, users, would love that 1.5.x gets more attention to the point to make it stable as soon as possible. Something like "forget about 1.4.x, it's stable, we only add a new version if it's a hotfix" and "turn all our efforts into 1.5.x"...

I use 1.5.x (my custom builds) for production and it works great (as great as 1.4.x does), hehehe

Anyway, it's your software, your time and your schedule, I don't mean to change anything, just to understand how works
;)

Cheers

**Comment by rodolforg** [comment] 2024-05-31 13:20
It isn't my software at all lol

Our big efforts are on master branch, and that's where the 1.5.x come from.

1.4.x is now on crash fix AFAIK.
See the release notes. Most of them came  from master branch. ;)
Currently there are no plans for 1.4.6 (AFAIK)

A critical issue we have is the mac port not being signed and not running in recent OS versions or processors.
But I don't have macOS as well as I don't know it lol
ice0 and konstantin are working on it

**Comment by pgilfernandez** [comment] 2024-06-07 07:40
> A critical issue we have is the mac port not being signed and not running in recent OS versions or processors.
> But I don't have macOS as well as I don't know it lol
> ice0 and konstantin are working on it

Nice, let's see how @ice0 and @morevnaproject work on it. I work on macOS so I'm able to help testing at any time, just let me know. =)

**Comment by rodolforg** [comment] 2024-09-06 06:16
- 1.4.5 was released and probably the last one for the 1.4.x branch
- 1.5.3 was released as current development release, up-to-date to master (until release date) and seems to be stable enough. Probably next release will be the next stable one.

**Closed by rodolforg** 2024-09-06 06:16 UTC
Labels: Not a bug, Fixed, Outdated
