### ISSUE TITLE
Zoom makes Synfig crash.

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#870] opened 2019-07-01 21:14 UTC
**Synfig version & platform**:
Master
Linux

**Issue description**:
Simple navigation using zoom makes Synfig crash, everywhere every time, with artwork or empty canvas, with prerender activated or without doesn't matter. 

[Video Demostration.](https://youtu.be/JYSEYNWSm4Y)

**Comment by BobSynfig** [comment] 2019-07-02 05:13
Please see my remark here: https://github.com/synfig/synfig/issues/674

**Comment by blackwarthog** [comment] 2019-07-17 05:16
fixed in 717751e

**Comment by morevnaproject** [comment] 2019-08-09 13:51
Reopening because of ee269a82d9200 and https://github.com/synfig/synfig/issues/896#issuecomment-518352110

**Comment by ebarranco** [comment] 2019-09-08 23:33
This is back, it is less often but still happening.

**Comment by blackwarthog** [comment] 2019-10-12 08:04
i've fixed some bugs by the commit 82ffbee5a24576138a7d3bfb7abd84dd4988182a
please recheck

**Comment by ebarranco** [comment] 2019-10-12 18:46
Hi @blackwarthog  I checked this issue again and it is totally back and I can reproduce the crashing every time.
[Video.](https://youtu.be/1vnWFtLLxMY)

**Comment by blackwarthog** [comment] 2019-10-13 07:13
> Hi @blackwarthog  I checked this issue again and it is totally back and I can reproduce the crashing every time.
> [Video.](https://youtu.be/1vnWFtLLxMY)

Thanks for your help, for me it reproduces after a several munutes of zoomming and scrolling. I've catch and fixed one more bug in this commit: 5fc8322664e53a2a139384d42f3444c8f0806883. May you check?

**Comment by ebarranco** [comment] 2019-10-13 19:41
Hey @blackwarthog !  I've been trying to crash Synfig and I can't do it now.  :smiley:

**Closed** 2019-10-14 09:41 UTC

**Comment by ebarranco** [comment] 2019-10-14 15:46
Thank's!
