### ISSUE TITLE
Indication needed that rendering is in progress.

### ISSUE THREAD

**Issue by CoryAlbrecht** [synfig/synfig#383] opened 2017-06-30 17:08 UTC
There's no indication that rendering is is being done unless you happen to have started synfigstudio from a terminal and can watch output to stdout/stderr go past.

There needs to be a way to know when a render is complete when launched from synfigstudio.

Synfig Studio 1.0.2 on Ubuntu 16.04.2 GNOME

**Comment by caryoscelus** [comment] 2017-06-30 17:13
Check status panel under drawing area. At least in recent versions there are messages "Rendering.." and "File rendered successfully" in it.

**Comment by CoryAlbrecht** [comment] 2017-06-30 17:23
OK, yes. However, since that area changes if you do anything like move to a keyframe, the indicator needs to be separate so it does not get overwritten/hidden by any actions the user may take.

I would also suggest a way to cancel an in progress render.

**Comment by caryoscelus** [comment] 2017-06-30 17:41
All good ideas, but there doesn't seem to be (m)any devs still interested in synfig.

**Comment by wstaelens** [comment] 2018-10-03 09:58
>           All good ideas, but there doesn't seem to be (m)any devs still interested in synfig.

All these pay wall, donate walls and different paying sites for tutorials etc are keeping me a bit away from it...

**Comment by morevnaproject** [comment] 2018-10-03 15:57
> All these pay wall, donate walls and different paying sites for tutorials etc are keeping me a bit away from it...

We do not have donate wall - on our download page it is clearly indicated that you can enter "zero" in the price field to get a binary build for free. Also, anonymous download link is provided. 

![screenshot_001](https://user-images.githubusercontent.com/332868/46422413-85c60300-c75e-11e8-97d6-84a013dd359a.png)

So, no wall - it is free for anyone who is able to read. ^__^

Having this suggestion to donate on the download page allows us to keep two developers contributing regularly to Synfig code. I invite you to check commits activity [here](https://github.com/synfig/synfig/graphs/commit-activity) and [here](https://github.com/synfig/synfig/commits/master) to see the impact they do.
All those regular contributions are possible thanks to donations we get from\ Download page.

Regarding paid tutorials - yes, we do have **one** paid training video course (translated in several languages), which also helps  to pay for efforts of our main developers. For those who do not want to get a paid course we have free tutorials and manual pages here - https://wiki.synfig.org/Category:Manual

Again, it is free for anyone who is able to read. ^__^

**Comment by morevnaproject** [comment] 2018-10-04 07:52
Blender had a massive community before it even become open-source, which paid a huge amount to make it free. Synfig's community is much smaller and didn't had that. We adopt some strategies from Blender (like selling tutorials - they do so via Blender cloud), but simple copy-monkey approach not always works, especially considering that Synfig lags ~5 years behind Blender.

I am contributing to Synfig since 2007 and tried various approaches already. In 2013-2014 I was running a crowdfunding campaigns every month to keep just one developer working on Synfig. That was exhausting and haven't allowed me to do any other things to keep project growing. With payments via donations page we have a regular flow of donations, which allows us to concentrate our limited resources on making the software better.

I understand your rant, but at the moment this is exact thing which allows project to survive and leaves resource for growing. ^__^

**Comment by morevnaproject** [comment] 2019-01-04 15:38
The issue is fixed now by #699! Will be shipped with next release of Synfig.

**Closed by morevnaproject** 2019-01-04 15:38 UTC
