### ISSUE TITLE
Pirates.sifz crashes

### ISSUE THREAD

**Issue by genete** [synfig/synfig#319] opened 2017-01-31 11:22 UTC
**synfigstudio 1.3.0 20170114 Windows XP:**

**Issue description**:
Open examples/pirates.sifz and it crashes. 
Running with debug console mode doesn't seem to provide useful information:
After a bunch of falloff parameter rejection from Circle layers it shows this:
```
(synfigstudio.exe:5544): Gtk-WARNING **: Inserting action group 'mainwindow-rece
ntfiles' into UI manager which already has a group with this name


(synfigstudio.exe:5544): gtkmm-WARNING **: gtkmm: Attempt to call Gtk::manage()
on a Gtk::Window, but a Gtk::Window has no parent container to manage its lifeti
me.


(synfigstudio.exe:5544): GLib-GObject-WARNING **: value "3,000000" of type 'gflo
at' is invalid or out of range for property 'yalign' of type 'gfloat'

(synfigstudio.exe:5544): Gtk-WARNING **: Cannot connect attribute `canvas' for c
ell renderer class `gtkmm__CustomObject_N6studio22CellRenderer_TimeTrackE' since
 `canvas' is already attributed to column 6

(synfigstudio.exe:5544): Gtk-WARNING **: Cannot connect attribute `canvas' for c
ell renderer class `gtkmm__CustomObject_N6studio22CellRenderer_TimeTrackE' since
 `canvas' is already attributed to column 6

```
It closes immediately after show system message that program has crashed.

**Comment by caryoscelus** [comment] 2017-01-31 11:26
Can't reproduce in my build, so it might have been fixed in master.

**Comment by genete** [comment] 2017-01-31 11:33
I can reproduce it on OS X 10.2.2 with the same version of synfigstudio

**Comment by Darkspace65** [comment] 2017-01-31 11:42
Loads fine on Windows 10, Synfig 1.2.0. (still remains one of the best vectors made in Synfig).

**Comment by morevnaproject** [comment] 2017-02-08 10:35
@Darkspace65 Can you  please check this with 1.3.0?

**Comment by Darkspace65** [comment] 2017-02-08 11:20
@morevnaproject Loads and renders fine on Windows 10, Synfig 1.3.1

**Comment by ice0** [comment] 2018-05-23 14:16
@genete Hi! Can you check it with latest version?
https://github.com/synfig/synfig/releases

**Comment by FirasH** [comment] 2020-03-19 16:13
Cannot reproduce with my build of 1.5.0 4f6e09 on openSUSE 15.1

**Comment by ice0** [comment] 2020-03-23 08:27
Ok.Then I close this issue.

**Closed by ice0** 2020-03-23 08:27 UTC
Labels: Crash
