### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by mistymew** [synfig/synfig#393] opened 2017-07-14 20:50 UTC
When i download Synfig and open the setup wizard, it says, "A previous version of Synfig is installed on your device (Synfig1.20). Would you like to delete it first? 1: i've never installed it before. 2: if i click yes, it deletes it and goes back to the setup wizard. The setup wizard says that it will help me install Synfig 1.20. 
                                                                               What does this mean?!

**Comment by Keyikedalube** [comment] 2021-02-18 02:28
Do you still encounter this same issue with the new stable version 1.4?
If not then this issue is safe to be closed.

And to answer your question this could have been a bug in the installer program or maybe there were old synfig configuration files (though you say otherwise) conflicting with the installer program.

**Comment by Keyikedalube** [comment] 2021-04-20 12:53
> 1: i've never installed it before. 

Maybe someone installed it on your computer without your knowledge.

> 2: if i click yes, it deletes it and goes back to the setup wizard. 

Going back to the setup wizard is intentional after deleting old synfig program files. Because the purpose of the setup wizard is to install the software which you haven't yet since it conflicts with the old installed synfig program even though you say you haven't, the installer program detected it.

> The setup wizard says that it will help me install Synfig 1.20. 
What does this mean?!

The means Synfig is now ready to be installed after successfully uninstalling your old synfig programs :)

BTW, I tried installing synfig 1.2.2 on Windows 8 to see if your issue can be reproducible without synfig pre-installed

https://user-images.githubusercontent.com/24214509/115398146-77e50a00-a204-11eb-8461-95950feaa2e9.mov

In my case, it doesn't complain about your stated "A previous version of Synfig is installed on your device (Synfig1.20). Would you like to delete it first?". So the installer program works fine as intended.

I believe I answered your question. Closing this issue.

**Closed by Keyikedalube** 2021-04-20 12:53 UTC
