### ISSUE TITLE
Improvement for the smoothmove tool

### ISSUE THREAD

**Issue by yshkp** [synfig/synfig#774] opened 2019-03-17 11:09 UTC
**Synfig version & platform**:
1.3.11 on Linux 

**Issue description**:
When you select the tool and try to drag the layer having fixed parameters it doesn't work. It works with dynamic parameter changes when all the handles selected with dragging of the layer which may be not effective when the user wants to move it.

**Comment by morevnaproject** [comment] 2019-03-17 12:59
Sorry, I didn't understood what you mean. Can you please clarify what "layer having fixed parameters" means? (maybe recording a video will help ^__^).

**Comment by yshkp** [comment] 2019-03-17 13:05
@morevnaproject I found out that when we want to drag a layer (for ex. rectangle) with all handles selected using smoothmove tool, it's size changes while dragging to a new location this is not a good thing. So, I think a fix requires which makes us able to drag the layer without changing its size.

**Comment by morevnaproject** [comment] 2019-03-17 13:10
Ah, this is an expected behavior. ^__^
Smooth Move tool is for deforming shapes. Please check this page for details - https://wiki.synfig.org/Smooth_Move_Tool

If you want to keep shape while moving, then use Transform Tool - 
![screenshot_013](https://user-images.githubusercontent.com/332868/54491341-6f68c980-48f0-11e9-9a5a-f41d1499084e.png)

**Comment by yshkp** [comment] 2019-03-17 13:17
@morevnaproject Yup I read that before, but I used this in rectangle layer which lacks the handle to drag the image using transform tool so I thought this tool can be used for this. But all other geometrical layers have the handle for moving the shape.

**Comment by morevnaproject** [comment] 2019-03-17 14:18
BTW, this raises up a good point: we probably should change icon for Smooth Move tool, so it will more clearly indicate its role. Users often get confused by this icon.

**Comment by morevnaproject** [comment] 2019-03-17 14:24
Added this as #775.

**Comment by yshkp** [comment] 2019-03-18 04:39
@morevnaproject Thanks.
I think it raises one more point for the rectangle layer to create one more such handle to move it around the canvas.

**Comment by michaelclapham** [comment] 2020-02-17 12:25
Being able to move objects with one click is a feature that Inkscape and other graphics packages have. Why not make the tool that currently looks like a drag tool, do exactly that? Having additional steps for such a common action currently means I can't use Synfig for teaching. 

Is there a way to drag an object with a single click without resizing that I'm not aware of? Increasing the radius on smooth move tool is not working for me.

**Comment by Keyikedalube** [comment] 2022-01-03 16:04
Closing this. Explained [here](https://github.com/synfig/synfig/issues/774#issuecomment-473664299)

**Closed by Keyikedalube** 2022-01-03 16:04 UTC
Labels: reminder
