### ISSUE TITLE
Windows: Ctrl+V and Ctrl+C is not context sensitive

### ISSUE THREAD

**Issue by keithnbrowncarlisle** [synfig/synfig#292] opened 2016-12-06 15:24 UTC
**Synfig version & platform**: Windows 1.0.2

**Issue description**:
When in a text field (layer description, file path, etc) with text info on the system clipboard, pressing Ctrl+V does not paste the text on the clipboard, nor does Ctrl+C copy any selected text.

The respective combinations only seem to work on layers, rather than individual pieces of text in properties. While the context menu still allows copying and pasting of text, this does not replace what is on the system clipboard.

This is rather unintuitive behavior.

**Comment by caryoscelus** [comment] 2016-12-06 15:29
This is duplicate of https://github.com/synfig/synfig/issues/257

**Closed by caryoscelus** 2016-12-06 15:29 UTC
