### ISSUE TITLE
Python binary file not found when exporting Lottie.json

### ISSUE THREAD

**Issue by JoedsonGabriel** [synfig/synfig#2596] opened 2022-03-29 12:34 UTC
**Describe the bug**

When trying to export a "lottie.json" file, a message is displayed stating that the python binary needs to be defined in the environment variable.

* Added SYNFIG_PYTHON_BINARY variable
* Restarted Windows
* I tried exporting again

Even so Synfig doesn't seem to recognize the new variable.

Detail: python 3.10 is already installed with their respective variables configured.

**To Reproduce**

1. Go to File
2. Click on Export
3. Select Lottie.json as file extension and save
4. See the error
![image](https://user-images.githubusercontent.com/45566621/160611291-4259ae47-4adf-4119-a0d8-164524dfbc42.png)

**System information:**
 - OS: [Windows]
 - OS version: 21H2
 - Synfig version: 1.5.1

**Additional comments**
Thank you

**Comment by ice0** [comment] 2022-03-30 05:10
@JoedsonGabriel 

Confirmed.

The problem occurs when there are spaces in the path to Python.
As a workaround, copy Python folder from "Program Files" to a folder that does not contain spaces.

**Comment by BobSynfig** [comment] 2022-04-03 15:18
In you Environment Variable, use the short version 8.3 instead of LFN for the path (C:\Progra~1\Python310\python.exe)
Anyway you will encounter the missing helper bug with this build (https://github.com/synfig/synfig/issues/2393) ... which can be solved easily too but leads once again to another bug!

**Comment by morevnaproject** [comment] 2022-04-05 03:08
Hi! Python is shipped with Synfig installation package, so it should work out-of-box without any external Python installation.
The error message may occur if you are trying to run plugin on unsaved file. 

@JoedsonGabriel can you please check if the error present if you try to run plugin on previously saved file? (without SYNFIG_PYTHON_BINARY env variable)

**Comment by ice0** [comment] 2022-04-05 05:03
@morevnaproject 
As BobSynfig already noted, we also have a problem with a missing `gspawn-win64-helper.exe` executable in the 1.5.1 release. (https://github.com/synfig/synfig/issues/2393).

It is required to run Python.

**Comment by morevnaproject** [comment] 2022-04-05 14:20
Ah, sorry I missed that note. Fixed via https://github.com/morevnaproject/morevna-builds/pull/44 ^__^

P.S. Surprisingly I haven't encountered errors with running python scripts on my Windows instance, but it might be because I am on Windows 8, not Windows 10.

**Comment by morevnaproject** [comment] 2022-04-05 15:30
Please check testing build - [SynfigStudio-1.4.3-testing-2022.04.05-win64-71775.exe](https://cloud.morevnaproject.org/s/NrH2Dx8DFL4dtNT)

**Comment by BobSynfig** [comment] 2022-04-07 15:53
I just tried (W10), it works as expected :)

**Closed** 2022-04-15 15:12 UTC
Labels: Windows, Bug
