### ISSUE TITLE
Synfig Studio segfaults when jumping to key frames

### ISSUE THREAD

**Issue by CoryAlbrecht** [synfig/synfig#387] opened 2017-07-06 21:09 UTC
Synfig Studio 1.0.3 on Ubuntu 16.04.2 GNOME

When jumping backwards to the previous key frame, Synfig Studio crashes with a segfault.

This happens mostly when using the keyboard, but occasionally when clicking the the "JMP" link in the panel, and usually when jumping back from the final frame, though occasionally from non-terminal key frames.

**Comment by CoryAlbrecht** [comment] 2017-08-14 14:53
Typo, that should be 1.0.2, what gets installed by apt-get on Ubuntu.

**Comment by Keyikedalube** [comment] 2021-08-16 13:52
> This happens mostly when using the keyboard

I can't reproduce this on the latest stable release 1.4.2

I think this issue must have been fixed by someone else

**Comment by Keyikedalube** [comment] 2022-01-03 16:57
Closing this because the Synfig version addressed here is dated and all patches are done on the latest stable/development releases.

Feel free to open a new issue if this is reproducible on current releases.

**Closed by Keyikedalube** 2022-01-03 16:57 UTC
Labels: Crash, Outdated, reminder
