### ISSUE TITLE
Crash on "rotate order" action on spline

### ISSUE THREAD

**Issue by caryoscelus** [synfig/synfig#280] opened 2016-11-04 18:13 UTC
```
synfigstudio: actions/valuenodedynamiclistinsert.cpp:204: virtual void synfigapp::Action::ValueNodeDynamicListInsert::perform(): Assertion `list_entry.value_node.rcount()==1' failed.
```

**Comment by genete** [comment] 2017-01-31 10:34
Can't reproduce on 1.3.0 revision 20170114 on Windows XP 32 bits

**Comment by caryoscelus** [comment] 2017-01-31 11:23
Can't reproduce crash in latest version either, but rotation doesn't seem to work when attempting to do it from the first element. Rotating from other elements seems to work fine.

**Comment by morevnaproject** [comment] 2017-02-01 12:47
Rotation always performs _relatively_ to element you clicking on. THis is why you see no change when clicking on first element.

**Comment by caryoscelus** [comment] 2017-02-01 13:40
Oh well, the crash happens to me again (also tried 1.0.2 - it's present there as well). Should investigate what are the specific conditions of it some time.

As for what it does: does it mean that it places selected element first in the list? If so, i think it should be clarified in the action name.

**Comment by morevnaproject** [comment] 2017-02-01 15:43
> As for what it does: does it mean that it places selected element first in the list? 

It seems so.

>If so, i think it should be clarified in the action name.

Agree.

**Comment by rodolforg** [comment] 2020-02-26 23:19
This problem was introduce by commit 790e124bea30a2e4b23166559c9a7582760eddda.

https://github.com/synfig/synfig/blob/790e124bea30a2e4b23166559c9a7582760eddda/synfig-studio/src/synfigapp/actions/valuenodedynamiclistinsert.cpp#L204

As I don't understand `rcount` ("number of reversible instances" [??] of `rhandle` "Replaceable Object Handle" [???]), I don't know if it should be always equal to 1 as  `assert` requires. If it should be simply greater than 1, code doesn't crash and appears to work fine.

**Comment by rodolforg** [comment] 2020-02-27 01:02
@blackwarthog could you please review this assert?

**Comment by blackwarthog** [comment] 2020-02-27 04:44
> As I don't understand rcount ("number of reversible instances" [??] of rhandle "Replaceable Object Handle" [???]), I don't know if it should be always equal to 1 as assert requires. If it should be simply greater than 1, code doesn't crash and appears to work fine via context menu in work area.

etl::handle - is a pointer with ref-count, like Glib::RefPtr. Contained object must be subclass of etl::shared_object and has methods ref(), unref() and count()

Where count is the count of etl::handles that holds this object, when count becomes zero by calling unref() object will deleted. We must remember that initially count() is zero and we must be careful is cases when object already created but yet not assigned to any handle. For example if we temporary store object in handle in constructor (for passing into some function for ex.) our object will deleted with this handle.

etl::'r'handle - extention of etl::handle that add new feature - ability to replace object in all rhandles that are containing it (method replace()). Contained object must be subclass of etl::'r'shared_object and has methods from simple shared_object: ref(), unref() and count(), and additional: rref(), runref() and rcount().

'r'shared_object contains a linked list of rhandles that holds this objects.

also we have the etl::loose_handle - it wraps pointer into class like handle but does not contain any logic and works like pointer. I understand a passing object by loose_hadle (instead of pointer) as sign that object is already holded by one or more handles in outside and i can use handles too (see example before)

**Comment by blackwarthog** [comment] 2020-02-27 05:01
> @blackwarthog could you please review this assert?

seems assertions only have a sence when 'item' field is not set.
in other case we must to remember state of item->rcount() before assignment:

	#ifndef NDEBUG
	int prev_rcount = item ? item->rcount() : 0;
	#endif
	list_entry=value_node->create_list_entry(index,time,origin);
	if(item)
	{
		list_entry.value_node=item;
	}
	else
	if (force_link_radius)
	{
		ValueNode_Composite::Handle composite = ValueNode_Composite::Handle::cast_dynamic(list_entry.value_node);
		if (composite && composite->get_type() == type_bline_point)
			composite->set_link("split_radius", ValueNode_Const::create(false));
	}
	assert(list_entry.value_node.rcount()==prev_rcount+1);

	value_node->add(list_entry,index);
	assert(list_entry.value_node.rcount()>=2);

but i yet does not know from that kind of bugs should protect this assertion

**Comment by blackwarthog** [comment] 2020-02-27 05:15
hm... i've looked previous code by darco and seems actions expects that item with zero rcount. i doesn know why.
may be it have a logic, may be item param was intoduced a bit later than assert and it's just bug.

seems these assertions is the traces of some anchient dubug process

**Comment by rodolforg** [comment] 2020-04-14 19:55
It doesn't crash anymore due to recent commits in production version.
In debug version, however, it crashes due to the mentioned assert.

**Comment by morevnaproject** [comment] 2020-04-23 17:15
So, should we close this issue?

**Comment by rodolforg** [comment] 2020-04-23 17:48
I really don't know what to do with mentioned assert :(

**Comment by morevnaproject** [comment] 2020-08-03 09:08
Is it okay to close this? ^__^

**Comment by ice0** [comment] 2020-08-03 11:37
Sure )

**Closed by ice0** 2020-08-03 11:37 UTC
Labels: Crash, Editing
