### ISSUE TITLE
Zoom in offset

### ISSUE THREAD

**Issue by ebarranco** [synfig/synfig#472] opened 2017-12-09 05:08 UTC
**Synfig version & platform**:
SynfigStudio-1.3.4-64bit-linux-testing-17.08.09
SynfigStudio-1.2.1-64bit
Manjaro KDE Edition 17.0.6
**Issue description**:
When you do it Zoom in, and you have activated Low Res, the art is offset from the vertices.
[Video](https://www.dropbox.com/s/8vhqmmcjfj6k3cv/Synfig_Bug_Lowres_offset.mp4?dl=0)

**Comment by caryoscelus** [comment] 2017-12-09 13:30
Duplicate of #273, and i can't reproduce it anymore on current master. See also #401. Apparently the build you're using is earlier than the fix.

**Closed by caryoscelus** 2017-12-09 13:30 UTC

**Comment by morevnaproject** [comment] 2017-12-11 05:46
This fix will be shipped with upcoming 1.3.5 build.

**Comment by morevnaproject** [comment] 2017-12-11 06:07
@ebarranco Although 1.3.5 is not officially announced yet, you can test its Linux builds already -
https://dev.icystar.com/downloads/SynfigStudio-1.3.5-testing-17.11.23-linux32-c2d19.appimage
https://dev.icystar.com/downloads/SynfigStudio-1.3.5-testing-17.11.23-linux64-c2d19.appimage

**Comment by ebarranco** [comment] 2017-12-11 06:33
ok, thanks @morevnaproject
