### ISSUE TITLE
Synfig Studio canvas rulers and coordinate system are contradictory and confusing.

### ISSUE THREAD

**Issue by CoryAlbrecht** [synfig/synfig#404] opened 2017-08-14 21:39 UTC
Synfig Studio 1.0.2 on Ubuntu GNOME 16.04.2

The coordinate systems used by the rulers in the canvas panel do not match what you need to enter in the Origin field in the properties panel.

For the canvas rulers to the right and up are positive while to the left and down are negative. However, to place an object in the upper right quadrant, instead of entering two positive values for the coordinates as one would expect based on the floating markers on the canvas rulers, one must actually enter two negative values.

![image](https://user-images.githubusercontent.com/8172909/29292912-fa306878-8116-11e7-846a-4d3369545810.png)

This is confusing as is compounded by there not being any current coordinates display when the mouse pointer is over the canvas.

**Comment by Keyikedalube** [comment] 2021-07-13 08:18
The coordinate ruler works as intended

Below is a simple circle layer demonstration

https://user-images.githubusercontent.com/24214509/125414638-c069ad3f-d5bc-418a-b2c6-11a5e12a0b12.mp4

The reason why you have to work around with negative values in the upper right quadrant is because of complex grouping.
For instance, below is an example where I draw a rectangle layer and group it then I move the handle to rect's origin so now like you I have to work around with reference values from the correct origin because my origin is fake.

What that means is you have to be aware of transformation values when grouping layers.

https://user-images.githubusercontent.com/24214509/125416518-60e3476d-57a8-4bec-8e88-c7634cad26c8.mp4

**Comment by Keyikedalube** [comment] 2022-01-03 16:37
Hope my above comment rectified your issue. I'm closing this but feel free to reopen if I made a mistake.

**Closed by Keyikedalube** 2022-01-03 16:37 UTC
Labels: reminder
