### ISSUE TITLE
"Edit in External Tool" Options

### ISSUE THREAD

**Issue by libreartist** [synfig/synfig#516] opened 2018-04-03 03:28 UTC
**Synfig version & platform**: 1.31, Debian (Sid)

**Issue description**: I recently noticed in LibreOffice that it has right-click option on its objects (like vectors, images, sound files and video). If clicked, that particular object will be opened in external application (the default one for those kind of files in your system, e.g., gimp for raster images, inkscape for vector images, ardour for sound files, etc.), so that we can edit them and save them directly into the document, not externally. Thus, it allows a workflow where the parts can be updated while they being positioned in the document. Can it be done in Synfig, for its raster images, vector images and sound files -- if they be needing editing while the project has already crossed the half-way?

**Comment by morevnaproject** [comment] 2018-04-04 13:57
Sounds good!

**Comment by morevnaproject** [comment] 2018-04-04 13:57
Related to https://github.com/synfig/synfig/issues/513

**Comment by morevnaproject** [comment] 2019-03-03 17:14
Let's start by implementing this for Image Layers only.

What is expected:

1. New option in Preferences of Synfig Studio, which defines a path to application for opening image files ("krita" or "gimp" or similar).
2. User can right-click any image and choose "Edit in external application..." menu item. This should open a image file in application specified in Preferences.

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-03 17:57
Thanks for referring this issue @morevnaproject have my exam on Monday so will be unresponsive for 2 days. 
And yes assign this one to me :grin:

**Comment by morevnaproject** [comment] 2019-03-04 08:26
Great! This issue is yours now. ^__^

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-08 13:34
@morevnaproject working on it now :)

**Comment by morevnaproject** [comment] 2019-03-08 18:34
By default Synfig doesn't embeds images into its files. It just references them.
You can obtain image path from image layer - 

![screenshot_001](https://user-images.githubusercontent.com/332868/54048053-3f903680-420b-11e9-80bb-fd189a2f9a9e.png)

So, all you need to do is to launch binary (the one specified in preferences) and pass an image path as an argument to it. I.e.:

```
/usr/bin/krita /path/to/some/file.png
```

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-08 18:54
@morevnaproject will send a PR tomorrow :)

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-09 10:10
> So, all you need to do is to launch binary (the one specified in preferences) and pass an image path as an argument to it. I.e.:
> 
> ```
> /usr/bin/Krita /path/to/some/file.png
> ```

@morevnaproject I saw the code of LibreOffice for "Edit in external tool" they save the image temporarily somewhere and "edit" works on that local copy, not on the original one. 

> `/usr/bin/krita /path/to/some/file.png`

This will, however, change the original file which I think not all user wants 
So what I am thinking now
- add an option Preferred image editor in preferences
![Untitled Diagram](https://user-images.githubusercontent.com/37617951/54069820-b74c7880-4280-11e9-828c-4c30f5c4d1ca.png)

- point the original image unless the user edits that using an external edit tool.
- when the edit is done the local copy (not the original one) will be modified.
- on subsequent edit local copy will be used. 
- As the local copy can be edited by external tool so it's source may not be needed by user hence will not be shown to him.

I have started working as I described. kindly let me know if I need to change something else
:)

**Comment by morevnaproject** [comment] 2019-03-09 15:23
>>    /usr/bin/krita /path/to/some/file.png
>
> This will, however, change the original file which I think not all user wants

Still, we would expect original file to be edited. So, here I have to insist - please make edits on original file. ^__^

**Comment by morevnaproject** [comment] 2019-03-09 16:14
Also, here is what I've just found:

![screenshot_002](https://user-images.githubusercontent.com/332868/54073479-30b48d00-42ba-11e9-91a3-cca8e7d10736.png)

If you import an image, then expand a yellow group and right-click a layer inside, then you can see there is already "Open file ..." menu item exists.

The code for it can be found here:

https://github.com/synfig/synfig/blob/f1244c28e1a7407570abdd243c489c46af6ebb5c/synfig-studio/src/gui/instance.cpp#L1716-L1749

The problems with current implementation:

* It uses ```App::open_uri()``` function, which relies on OS file associations. It doesn't works for me when I am trying to open PNG files. Also, the OS file associations could be not a best choice when we want to edit PNG files (I usually associate PNG files with some viewer, not editor). So, let's go with an  Preferred Image Editor option in preferences.
* Second: it is not very  convenient to expand yellow group and right-click layer inside. This is not intuitive. It would be better to have this option for yellow group itself. The problem is that yellow groups are actually can contain something else than image layer (this is because they are general-purpose switch groups). As a solution we need a special condition, which will check if yellow group has (a single) image layer inside. If yes - then "Open file ..." option is displayed.

How to achieve last requirement?

There is already similar case, which can help to understand how to implement this.

Synfig has support for Papagayo lipsync files - PGO. Here is how it works - https://www.youtube.com/watch?v=-Y0Ox0cnlL4

This feature is interesting for us, because it adds "Open file ..." action to group menu, IF some of group's parameters references a filename:

![screenshot_006](https://user-images.githubusercontent.com/332868/54074079-cb17cf00-42c0-11e9-8c43-02f3fdac2dce.png)

See ```gather_uri()``` functions responsible for this in https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/instance.cpp#L1597

So, I think, it should be possible to add check if group has a single layer inside and this layer is image layer.

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-09 17:28
> Still, we would expect original file to be edited. So, here I have to insist - please make edits on original file. ^__^

Sure @morevnaproject  :+1:  will make changes accordingly.

I have one concern when I create an image layer shouldn't synfig ask me? for image file :question:

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-09 18:00
> * It uses `App::open_uri()` function, which relies on OS file associations. It doesn't works for me when I am trying to open PNG files. Also, the OS file associations could be not a best choice when we want to edit PNG files (I usually associate PNG files with some viewer, not editor). So, let's go with an  Preferred Image Editor option in preferences.
> 
> *

I see this as this is also a problem with what libreoffice did (I am not sure if they upgraded) relying on OS file association is never a good idea :100:  This works for me as I have associated krita with png images. 

> So, I think, it should be possible to add check if group has a single layer inside and this layer is image layer.

Yes we can surely do that 
Thanks for the pointers @morevnaproject I will aslo add a prompt in case of 

> I am talking about layer->new layer->other->import image

**Comment by morevnaproject** [comment] 2019-03-11 10:07
> I have one concern when I create an image layer shouldn't synfig prompt ask me for image file? I am talking about layer->new layer->other->import image

Actually that would be cool addition! (this can be a separate PR, if you like) ^__^

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-11 15:05
@morevnaproject I am not able to completely understand the gather_uri() is it documented somewhere? 
@blackwarthog tagged you because you own this code :)
I appreciate if you can brief me a bit.
> See `gather_uri()` functions responsible for this in https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/instance.cpp#L1597

**Comment by blackwarthog** [comment] 2019-03-11 15:53
> @blackwarthog tagged you because you own this code :)
> I appreciate if you can brief me a bit.
> > See `gather_uri()` functions responsible for this in https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/instance.cpp#L1597

Instance::gather_uri() helps to find all external files that used in currently open canvas.
This fuction uses to find files for context menu items starting with 'Open file...'

There are several gather_uri() methods which called each other recursively, and root entry point is:
Instance::gather_uri(std::map<synfig::String, synfig::String> &x, const synfigapp::SelectionManager::LayerList &layers)

This function fills the dictionary 'x' with 'fullpaths by displaypaths':
  x[displaypath] = fullpath

Other overloads gather_uri are also usable for an corresponding entries of canvas hierarchy, but do not generates a display paths and fills only a simple list with full paths.

Currently gather_uri() uses only in
  Instance::add_special_layer_actions_to_menu and
  Instance::add_special_layer_actions_to_group
while buildind of a context menu.

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-12 18:41
>     * Second: it is not very  convenient to expand yellow group and right-click layer inside. This is not intuitive. It would be better to have this option for yellow group itself. The problem is that yellow groups are actually can contain something else than image layer (this is because they are general-purpose switch groups). As a solution we need a special condition, which will check if yellow group has (a single) image layer inside. If yes - then "Open file ..." option is displayed.

@morevnaproject sorry for the delay.
Maybe this might seem obvious to you but I am still struggling with the **second** I did not found any method to get the number of layers inside the switch layer
I looked https://github.com/synfig/synfig/blob/9d2e9afb0770b91d311ecc3f128e32736ba8b22d/synfig-core/src/synfig/layers/layer_switch.cpp
and https://github.com/synfig/synfig/blob/9d2e9afb0770b91d311ecc3f128e32736ba8b22d/synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp 
but still not found anything. I tried selecting all the layers using 
`	LayerTree::select_all_children_layers(synfig::Layer::Handle layers.front());
`
yet nothing good happened.
I don't know why i am not getting this :disappointed:

**Comment by morevnaproject** [comment] 2019-03-13 13:25
@ankit-kumar-dwivedi I need some time to think on the solution. While I am doing this (^__^) I suggest to make a PR for first part of this issue (about Preferred Image Editor option).

**Comment by morevnaproject** [comment] 2019-03-13 13:41
> Maybe this might seem obvious to you but I am still struggling with the second I did not found any method to get the number of layers inside the switch layer

I think the key is in lines 1657 and 1658 -
https://github.com/synfig/synfig/blob/a6476f206374ef2ecc430f137d24c5bfdb354faf/synfig-studio/src/gui/instance.cpp#L1630-L1659

```paste->get_param("canvas").get(Canvas::Handle())``` returns canvas and then you can get a list of its layers using ```get_layers_in_group()``` function.

https://github.com/synfig/synfig/blob/d4e64b6fbac082ab74bbc90360a2325c738d1015/synfig-core/src/synfig/canvas.h#L374-L375

@blackwarthog Am I right? ^__^

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-13 13:59
> `paste->get_param("canvas").get(Canvas::Handle())` returns canvas and then you can get a list of its layers using `get_layers_in_group()` function.

trying this now :smiley:

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-13 15:03
@morevnaproject 
I uncommented those lines

> I think the key is in lines 1657 and 1658 -

and added some **cout** to get information 
```
	if (etl::handle<Layer_PasteCanvas> paste = etl::handle<Layer_PasteCanvas>::cast_dynamic(layer)){
		std::cout<<"Some sweet info \n";
		std::cout<<"SIZE ==> "<<paste->get_param("canvas").get(Canvas::Handle())->get_groups().size();
		
	}
```
I am getting 0 here

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-13 15:07
> @ankit-kumar-dwivedi I need some time to think on the solution. While I am doing this (^__^) I suggest to make a PR for first part of this issue (about Preferred Image Editor option).

Sure I will do that :)

**Comment by ankit-kumar-dwivedi** [comment] 2019-03-14 09:56
@morevnaproject please have a look at PR :)

**Comment by ankit-kumar-dwivedi** [comment] 2019-04-02 18:35
@morevnaproject I am not getting any output for :arrow_down: after changing https://github.com/synfig/synfig/blob/a6476f206374ef2ecc430f137d24c5bfdb354faf/synfig-studio/src/gui/instance.cpp#L1704-L1707

to 
```
void
Instance::add_special_layer_actions_to_menu(Gtk::Menu *menu, const synfig::Layer::Handle &layer) const
{
	std::cout<<"You called me line 1706\n";
	add_special_layer_actions_to_menu(menu, synfigapp::SelectionManager::LayerList(1, layer));
}
```
However it is being called on line
https://github.com/synfig/synfig/blob/71802920181c984255c4351b876502ecfcbd4cb4/synfig-studio/src/gui/canvasview.cpp#L1711

This is the function responsible for adding "open file.." option in group menu right?

**Comment by morevnaproject** [comment] 2019-04-03 17:00
@ankit-kumar-dwivedi The part of code you referenced is called when you right-click a layer in workarea (CanvasView).

When you select a layer in Layer Panel it calls this - 
https://github.com/synfig/synfig/blob/71802920181c984255c4351b876502ecfcbd4cb4/synfig-studio/src/gui/instance.cpp#L1732-L1756

This function is called from 
https://github.com/synfig/synfig/blob/71802920181c984255c4351b876502ecfcbd4cb4/synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp#L320-L322

**Comment by ankit-kumar-dwivedi** [comment] 2019-04-03 17:27
@morevnaproject  and is there a separate function that is called when I right click a yellow switch group?

**Comment by ankit-kumar-dwivedi** [comment] 2019-04-04 17:58
@morevnaproject  I used the group layer and accessed the canvas using
 _layer->get_canvas()_ but when I tried using the function  
`std::set<etl::handle<Layer> > get_layers_in_group(const String&group); `
In return I am getting an empty set. 
so i changed the following
https://github.com/synfig/synfig/blob/a6476f206374ef2ecc430f137d24c5bfdb354faf/synfig-studio/src/gui/instance.cpp#L1630-L1659 and I am getting 0 after I wrote the following at line 1634.
``` 
int layerset = layer->get_canvas()->get_group_count();
std::cout<<std::endl<<"group count is : "<<layerset<<"\n";

``` 
I wish to know the number of layers inside the group layer which is passed to the gather_uri() function please let me know if am looking into wrong direction [^_^]

**Comment by morevnaproject** [comment] 2019-04-05 05:22
@ankit-kumar-dwivedi  I am afraid ```get_group_count()``` is not the right function to use, as it serves for different purpose ^__^ -

https://github.com/synfig/synfig/blob/6eafe8e0af292b65c2dd7d39822b7531da045bdc/synfig-core/src/synfig/canvas.h#L380-L381

You need to look for other function of Canvas class. ^__^

**Closed** 2019-04-07 14:10 UTC
Labels: Assigned, Feature request, good first issue, help wanted
