### ISSUE TITLE
SynfigStudio 1.2.1-20171013 causes memory manager to crash when launched!

### ISSUE THREAD

**Issue by JohnGregory1952** [synfig/synfig#501] opened 2018-03-10 01:11 UTC
**Synfig version & platform**:
SynfigStudio 1.2.1-20171013…2017 iMac 5K Retina. High Sierra 10.13.3. 16GIGS of RAM, 500GIG SSD.
**Issue description**:
Every time Synfig is launched it causes **_Memory Clean 3_** to crash. When that happens Synfig will work but cannot be quit by Command Q or via Menu. Must force quit the app to shut it down.

**Comment by Keyikedalube** [comment] 2022-01-03 16:31
Closing this because v1.2.1 stable release is old.

Latest stable release is now in v1.4.x
Please feel free to open a new issue if this is reproducible on current stable release.

**Closed by Keyikedalube** 2022-01-03 16:31 UTC
Labels: MacOS, Outdated, reminder
