### ISSUE TITLE
Graident rendering broken in v1.3.11

### ISSUE THREAD

**Issue by Kinoblit** [synfig/synfig#795] opened 2019-03-28 02:44 UTC
I took one of my files I made v1.2.1.  This is how it's supposed to look:
![good_render_1 13](https://user-images.githubusercontent.com/49011417/55125908-a786be00-50e1-11e9-8c57-303c0facf6b4.png)

v1.3.11 on Ubuntu (built from the source release tarball).  This is what's happening:
![bad_render_1 13](https://user-images.githubusercontent.com/49011417/55125872-8756ff00-50e1-11e9-8d50-1531bdea8f8d.png)

These are my layers.  I'm using the "Onto" blend method for the graidents
![layers](https://user-images.githubusercontent.com/49011417/55125935-cab16d80-50e1-11e9-8949-892dad263212.png)

**Comment by morevnaproject** [comment] 2019-03-28 12:36
Duplicate of #720. Fixed in master branch.

**Closed by morevnaproject** 2019-03-28 12:36 UTC
