### ISSUE TITLE
strange after skeleton deformation.?

### ISSUE THREAD

**Issue by manuelsongokuh** [synfig/synfig#345] opened 2017-04-12 21:45 UTC
version 1.2.0

i add shape "star" and add layer deformation, try to deformation and result bad draw..like as raster and is not vector..why?
see image:
![synfigstudio-strange](https://cloud.githubusercontent.com/assets/12126929/24980696/a329d152-1fd9-11e7-86f9-64d7a13cef18.png)

look here:
![synfigstudio-strange02](https://cloud.githubusercontent.com/assets/12126929/24980739/d26cb25e-1fd9-11e7-888b-78b240778080.png)

i try development version , open file saved is crashed..

[testing.zip](https://github.com/synfig/synfig/files/917923/testing.zip)

thank you

**Comment by Keyikedalube** [comment] 2021-07-13 05:25
> i add shape "star" and add layer deformation, try to deformation and result bad draw..like as raster and is not vector..why?

From https://wiki.synfig.org/Skeleton_Deformation_Layer

_Skeleton Deformation acts like a normal "raster" layer (i.e. Blur, Warp), it is a raster deformation._

Hence the blur effect on your vector star object. Hope that answers your question.


> i try development version , open file saved is crashed.

Latest stable release Synfig Studio 1.4.1 doesn't crash opening your saved file - not reproducible anymore

I'm closing this because the crash issue addresses old development version 1.3.x and the issue regarding rasterized output, I believe the wiki answered why.

**Closed by Keyikedalube** 2021-07-13 05:25 UTC
Labels: Crash, Outdated
