### ISSUE TITLE
Synfig Studio appImage 1.5.1 does not work with ArchLinux

### ISSUE THREAD

**Issue by Gilraiser** [synfig/synfig#2397] opened 2021-10-31 13:33 UTC
**Describe the bug**
The development version 1.5.1 AppImage does not run on the ArchLinux operating system. After having given the corresponding execution permissions, the information that the console returns is the following:

/tmp/.mount_pOKyZn/usr/bin/synfigstudio: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language

**To Reproduce**
1. Double click on the Synfig Studio appimage

**Expected behavior**
The program window with all its graphical interface should be displayed.

**System information:**
 - Linux distro: ArchLinux
 - Package: AppImage
 - Synfig version: 1.5.1

Thank you very much in advance for your attention
Excellent job developing Synfig Studio :)

**Comment by rodolforg** [comment] 2021-10-31 14:19
`hb_ot_tags_from_script_and_language` is a harfbuzz command.
Maybe the shipped version is too old?

**Comment by Gilraiser** [comment] 2021-10-31 16:01
Hi 
rodolforg. Please excuse me, because I do not understand what you wrote, but I have updated the operating system to date and the Synfig appimage I downloaded from the GitHub link.

On the other hand, with the name harfbuzz I have the following installed:

local/harfbuzz 3.0.0-1
    OpenType text shaping engine
local/harfbuzz-icu 3.0.0-1
    OpenType text shaping engine (ICU integration)
local/lib32-harfbuzz 3.0.0-1
    OpenType text shaping engine (32-bit)

I hope the information is useful to you.

Many thanks.

**Comment by Gilraiser** [comment] 2021-11-01 16:11
I tested on a virtual machine, with an ArchLinux without updating for several weeks. This OS had harfbuzz version 2.8.2-1 and Synfig 1.5.1 appimage ran successfully. After I upgraded this system the same problem occurred.

A week ago I compiled from the master branch this same version and I have not had any problems.

**Comment by rodolforg** [comment] 2021-11-01 16:20
Are you able to compile by yourself instead of using the AppImage?
I don't know anything about AppImage bundling, but this way we'll know if it is an AppImage package issue or library version mismatch.

Btw, since #2232 we depend on harfbuzz library.

**Comment by ice0** [comment] 2021-11-01 16:37
The problem is that we are bundling an old version of the harfbazz library, which requires old `lybreetype.so.6` library.
An easy solution - is not bundle it, and just use the system one.
Another solution is to add `libfreetype.so.6` to AppImage and check if it doesn't break anything.

**Comment by rodolforg** [comment] 2021-11-01 17:11
> Sorry I'm compiling from source, but I don't know how to package in appimage. I tried it once and it didn't work.

So you can't run Synfifg Studio you compiled yourself?

**Comment by Gilraiser** [comment] 2021-11-01 17:14
> > Sorry I'm compiling from source, but I don't know how to package in appimage. I tried it once and it didn't work.
> 
> So you can't run Synfifg Studio you compiled yourself?

The one I compiled from the master branch works fine when I run it. It is the appimage that you download from github version 1.5.1 that does not run and throws the error.

**Comment by Gilraiser** [comment] 2021-11-01 17:16
A thousand apologies if I did not make myself understood. I mean, I don't know how to create appimage packages.

**Comment by morevnaproject** [comment] 2021-11-15 15:24
@Gilraiser Can you please check if 1.5.0 appimage works for you?

> Another solution is to add `libfreetype.so.6` to AppImage

@ice0  :rofl: 
We have removed freetype from appimage after version 1.4.1 - https://github.com/morevnaproject/morevna-builds/commit/86e24a42a32241d3a8fb0b818cd7d0b6898bafcd
So, 1.4.2, 1.5.0 and 1.5.1 appimages do not include fontconfig/freetype.
This is done to fix fontconfig slow start problem - https://github.com/synfig/synfig/issues/1849 ^__^

I guess we can fix the issue if we will increase version of freetype used during appimage compilation.
Currently we use freetype-2.8.1

@Gilraiser Can you please let me know the version of freetype in your system?

**Comment by morevnaproject** [comment] 2021-11-15 15:26
Found relevant issue - https://bugs.archlinux.org/task/71680

**Comment by ice0** [comment] 2021-11-16 01:12
@morevnaproject 
> We have removed freetype from appimage after version 1.4.1

We have removed `fontconfig`. I'm not sure if `freetype` was removed as an unnecessary dependency of `fontconfig` or if it breaks something. That's why I suggested  to check this.

**Comment by Gilraiser** [comment] 2021-11-18 05:42
> @Gilraiser Can you please check if 1.5.0 appimage works for you?
> 
> > Another solution is to add `libfreetype.so.6` to AppImage
> 
> @ice0 rofl We have removed freetype from appimage after version 1.4.1 - [morevnaproject/morevna-builds@86e24a4](https://github.com/morevnaproject/morevna-builds/commit/86e24a42a32241d3a8fb0b818cd7d0b6898bafcd) So, 1.4.2, 1.5.0 and 1.5.1 appimages do not include fontconfig/freetype. This is done to fix fontconfig slow start problem - #1849 ^__^
> 
> I guess we can fix the issue if we will increase version of freetype used during appimage compilation. Currently we use freetype-2.8.1
> 
> @Gilraiser Can you please let me know the version of freetype in your system?

Hello, sorry for answering late. My version of freetype is freetype2 2.11.0-4. I hope it is still helpful.

**Comment by morevnaproject** [comment] 2021-11-29 15:02
> We have removed `fontconfig`. I'm not sure if `freetype` was removed as an unnecessary dependency of `fontconfig` or if it breaks something. That's why I suggested to check this.

Ah, I see now! "freetype" was required by "fontconfig". We ahve removed "fontconfig" and thus "freetype" was removed too.
You right, we can try to explicitly add freetype as dependency to synfig-core and see if that would work...

**Comment by morevnaproject** [comment] 2021-11-29 15:10
I have made a test changes on build server. Now rebuilding packages...

**Comment by morevnaproject** [comment] 2021-11-30 06:27
@Gilraiser @THEBATEZIOPARKER 
Here is the new testing package - https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.5.1-testing-2021.11.30-linux64-bef48.appimage
Can you please check if it solves the problem for you? ^__^

**Comment by THEBATEZIOPARKER** [comment] 2021-11-30 06:37
It Fixed The Old Error But Created New Error :-
https://user-images.githubusercontent.com/87817029/143997681-275b35df-ad36-4f43-b83e-6d480b51a705.png

**Comment by Gilraiser** [comment] 2021-12-04 13:54
Hi everyone. I get the same error reported by friend @THEBATEZIOPARKER in console: 

/tmp/.mount_qbvlWE/usr/bin/synfigstudio: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

**Comment by morevnaproject** [comment] 2021-12-13 13:44
@Gilraiser @THEBATEZIOPARKER  Thank you for testing and feedback!

Okay, so we had to ship both freetype and fontconfig.
And that means we had to solve problem with fontconfig cache.

I suggest to solve it by adding following stuff to Synfig's launcher script:
```
fc-cache |tee >(zenity --progress --pulsate --title="Fontconfig" --no-cancel --auto-close --text="Please wait, generating font cache...")
```
(found this here - https://stackoverflow.com/a/12407435)

Reopening #1849...

**Comment by ice0** [comment] 2021-12-13 13:57
@morevnaproject 
It looks like this window will blinks on every startup. I suggest adding the timestamp file and skipping this check if it has already been created. Maybe we can use Synfig config file for this?

**Comment by morevnaproject** [comment] 2021-12-13 14:07
But what if font configuration will change? (i.e. new font files added)
Then dialog will not be shown (because of timestamp file), but Synfig Studio will delay startup (because of font cache regenerated).


I can tweak a script to show progressbar window only after some delay. (0.5 seconds?)

**Comment by morevnaproject** [comment] 2021-12-13 14:16
> I can tweak a script to show progressbar window only after some delay. (0.5 seconds?)

```
(sleep 0.5 && zenity --progress --pulsate --title="Fontconfig" --no-cancel --auto-close --text="Please wait, generating font cache...") &
zpid=$!
fc-cache
kill $zpid
# run synfigstudio here...
```

**Comment by morevnaproject** [comment] 2021-12-13 14:24
Hmmm.. my last code doesn't work. :-/
I guess we have to deal with blinking window for now.

**Comment by morevnaproject** [comment] 2022-02-12 12:55
Related information - https://bugs.freedesktop.org/show_bug.cgi?id=101820

**Comment by morevnaproject** [comment] 2022-02-12 12:57
Related problem in Inkscape - https://bugs.launchpad.net/inkscape/+bug/1528629

**Comment by morevnaproject** [comment] 2022-02-15 10:02
I have implemented several changes to our build system, which should fix the issue:
- https://github.com/morevnaproject/morevna-builds/pull/33
- https://github.com/morevnaproject/morevna-builds/pull/36
- https://github.com/morevnaproject/morevna-builds/pull/37

As result, now it should display a notification window when font cache is generated.

Here is a package for testing, please check how it works for you -
[SynfigStudio-1.4.3-testing-2022.02.15-linux64-511af.appimage](https://cloud.morevnaproject.org/s/d8XPTBsDpBPKg8d)

You can simulate the "first start" behavior if you delete fontconfig cache in your user directory (`rm -rf $HOME/.cache/fontconfig/`).

**Comment by THEBATEZIOPARKER** [comment] 2022-02-15 15:19
@morevnaproject It Works

**Comment by ice0** [comment] 2022-02-23 03:24
Just checked on Manjaro/Ubuntu 21.04/Ubuntu 21.10
Everything works fine. So I am closing it. 

@Gilraiser please reopen this issue if you still experience the problem.

**Closed by ice0** 2022-02-23 03:24 UTC

**Comment by linkpy** [comment] 2022-08-15 10:57
hi

~~~~
$ ./SynfigStudio-1.5.1-2021.10.21-linux64-2cb6c.appimage
/tmp/.mount_ohdzZ7/usr/bin/synfigstudio: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
~~~~

system : 
~~~~
OS: Garuda Linux x86_64
Host: MS-7C52 1.0
Kernel: 5.18.16-zen1-1-zen
Shell: fish 3.5.1
~~~~

libraries : 
~~~~
extra/freetype2 2.12.1-1 [installed]
extra/harfbuzz 5.1.0-1 [installed]
~~~~

have any idea for a workaround?

**Comment by linkpy** [comment] 2022-08-15 11:25
it works by compiling synfig from sources.

**Comment by rodolforg** [comment] 2022-08-15 12:49
Try this intermediate release: https://cloud.morevnaproject.org/s/93e4cS78Y48AZPk

**Comment by linkpy** [comment] 2022-08-15 20:30
> Try this intermediate release: https://cloud.morevnaproject.org/s/93e4cS78Y48AZPk

this one works.

**Comment by rodolforg** [comment] 2022-08-15 20:57
Thank you.
