### ISSUE TITLE
[Lottie exporter] 004-image-group-cutout.sif fails to export

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#917] opened 2019-08-12 15:29 UTC
**Synfig version & platform**:
Commit id: 394aeeafd73c646c

**Issue description**:
Test file - https://github.com/synfig/synfig-tests-regressions/blob/master/export/lottie/004-image-group-cutout.sif

Error:
```
synfig(14100) [22:26:55] info: Traceback (most recent call last):
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/lottie-exporter.py", line 163, in <module>
    new_file_name = parse(FILE_NAME)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/lottie-exporter.py", line 68, in parse
    gen_layers(settings.lottie_format["layers"], canvas, canvas.get_num_layers() - 1)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/driver.py", line 81, in gen_layers
    itr)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/group.py", line 94, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas, canvas.get_num_layers())
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/sources/precomp.py", line 29, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], canvas, layer_itr-1)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/driver.py", line 81, in gen_layers
    itr)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/group.py", line 94, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas, canvas.get_num_layers())
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/sources/precomp.py", line 29, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], canvas, layer_itr-1)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/driver.py", line 81, in gen_layers
    itr)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/group.py", line 94, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas, canvas.get_num_layers())
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/sources/precomp.py", line 29, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], canvas, layer_itr-1)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/driver.py", line 81, in gen_layers
    itr)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/group.py", line 94, in gen_layer_group
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], canvas, canvas.get_num_layers())
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/sources/precomp.py", line 29, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], canvas, layer_itr-1)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/driver.py", line 76, in gen_layers
    itr)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/preComp.py", line 49, in gen_layer_precomp
    asset = add_precomp_asset(settings.lottie_format["assets"][-1], layer.getparent(), idx)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/sources/precomp.py", line 29, in add_precomp_asset
    layers.driver.gen_layers(lottie["layers"], canvas, layer_itr-1)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/driver.py", line 81, in gen_layers
    itr)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/layers/group.py", line 75, in gen_layer_group
    scale.animate("group_layer_scale")
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/common/Param.py", line 203, in animate
    self.recur_animate(anim_type)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/common/Param.py", line 346, in recur_animate
    scalar, eff_2 = self.subparams["scale"].subparams["scalar"].recur_animate("scalar_multiply")
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/common/Param.py", line 450, in recur_animate
    self.gen_path("real")   # "real" can be of various types as defined in common.misc.parse_position()
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/common/Param.py", line 513, in gen_path
    gen_value_Keyframed(self.path, self.param[0], idx)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/properties/valueKeyframed.py", line 31, in gen_value_Keyframed
    gen_value_Keyframe(lottie["k"], animated, i)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/properties/valueKeyframe.py", line 114, in gen_value_Keyframe
    cur_pos = parse_position(animated, i)
  File "/home/konstantin/sources/synfig.lottie/_production/build/share/synfig/plugins/lottie-exporter/common/misc.py", line 100, in parse_position
    pos = [float(animated[i][0].attrib["value"]),
  File "src/lxml/etree.pyx", line 2457, in lxml.etree._Attrib.__getitem__
KeyError: 'value'
```

**Comment by AnishGG** [comment] 2019-08-20 15:34
For this, I am getting an error when I open the file in Synfig. 
Here it is:
```
/home/anishg/GSOC/final/synfig-tests-regressions/export/lottie/004-image-group-cutout.sif:<string>:401: Layer 'import' rejected value for parameter 'filename'
```
I am getting this for all the `import` layers. The path seems to be correct, but I am not able to find the mistake.
@morevnaproject any help here... ^_^
Thank you!

**Comment by morevnaproject** [comment] 2019-08-22 09:22
That's weird... I cannot reproduce that error. Can you please record a video of your screenso I can see what's happening? ^__^

**Comment by AnishGG** [comment] 2019-08-22 13:19
There might be a problem with the version of Synfig I am using. I will reinstall it with the latest master branch and try again.
If the problem still exists, I will report here.

**Comment by AnishGG** [comment] 2019-08-22 14:46
@morevnaproject, I tried as mentioned above also, but the import still fails.
I have uploaded a video demonstrating the same: https://youtu.be/MQpTwVGDfgg
Please guide furthur.

**Comment by morevnaproject** [comment] 2019-08-23 11:43
I suspect your build of Synfig is missing PNG support. Can you please create empty document and try to import any PNG file?

**Comment by AnishGG** [comment] 2019-08-29 17:41
Yes, I tried importing a png file. It fails and the warning is: `unable to import path/to/file`. 
Any suggestions on how to get rid of this error?

**Comment by morevnaproject** [comment] 2019-08-31 06:04
That means you do not have "libpng" dev package installed. On Ubuntu/Debian/Mint the package is called `libpng-dev`. On Fedora it is called `libpng-devel`.

**Comment by AnishGG** [comment] 2019-09-01 05:51
@morevnaproject It is already installed on my system. Still I am getting that error. :confused:

**Comment by AnishGG** [comment] 2019-09-01 05:58
I have two versions of Synfig installed on my system. Can that be causing this error?

**Comment by AnishGG** [comment] 2019-09-03 17:15
@morevnaproject, I just realized that the png format images uploaded on synfig-tests-regressions looks like:

https://github.com/synfig/synfig-tests-regressions/blob/d1390e500d37ac79a4041ce5423f387c90724b78/export/lottie/004-image-group-cutout.files/head.png#L1-L3

I am not even able to open those png images from a regular image opener. Could you please check from your side if these are the correct images.

**Comment by morevnaproject** [comment] 2019-10-28 15:31
Now our tests  repository is moved to https://gitlab.com/synfig/synfig-tests

Here is an updated link to sample file - https://gitlab.com/synfig/synfig-tests/blob/master/export/lottie/004-image-group-cutout.sif (you will need to fetch whole repository to get all images in place).

**Comment by AnishGG** [comment] 2019-11-23 10:07
@morevnaproject, Apologies for late reply.
So we are facing this issue because the animation uses "exp" convert type, which I did not support yet.
Will provide support for it soon.

**Comment by AnishGG** [comment] 2019-11-24 13:41
Support for "exponent" is almost done. The only remaining part is the expression of "exp" in Lottie. I am not able to figure out what lottie uses, because the trial period of Adobe after effects has ended for me. 
Can someone help me here?

**Comment by AnishGG** [comment] 2019-11-26 17:41
This is now resolved by the above commit.

**Comment by morevnaproject** [comment] 2019-11-27 07:26
Confirmed it is working now! So awesome to see cutout animation in browser! :tada:

**Closed** 2019-11-27 07:29 UTC
