### ISSUE TITLE
"Lock Selection" parameter of Group Layer should be static by default

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#780] opened 2019-03-18 08:26 UTC
See https://wiki.synfig.org/Static_Parameters

When Group is created, it has "Blend Method" and "Z Range" parameters marked as static by default -
![screenshot_008](https://user-images.githubusercontent.com/332868/54516652-223d3400-4992-11e9-91ad-7522ab8711f8.png)

It is reasonable to have "Lock Selection" parameter static by default as well.

**Comment by ani1998ket** [comment] 2019-03-19 08:09
i want to work on this issue. could you please guide me where to start

**Comment by ani1998ket** [comment] 2019-03-19 09:11
i think its already solved when the opened the file the lock selection was already set to static

**Comment by morevnaproject** [comment] 2019-03-20 08:43
@ani1998ket It looks like it isn't. Steps to reproduce:

- Create empty document in Synfig
- Create Circle Layer
- Group it
- See "Lock Selection" Parameter in Parameters Panel - it is not static.

![screenshot_002](https://user-images.githubusercontent.com/332868/54670719-d96ab400-4b26-11e9-91d1-adbb1e36ebe9.png)

**Comment by maitreyi0505** [comment] 2019-03-22 14:03
I've been looking at the issue for quite some time, suggested changes according to my understanding:
In the following files,
[https://github.com/synfig/synfig/blob/master/synfig-studio/images/background_rendering_icon.sif](url)
[https://github.com/synfig/synfig/blob/master/synfig-studio/images/background_rendering_icon.sif](url)
Blend mode and Z range have been written as
`    <param name="z_range">
      <bool value="false" static="true"/>
    </param>`
and 
`   <param name="z_range">
      <bool value="false" static="true"/>
    </param>`

So I think we need to change Lock Selection form:
`    
    <param name="children_lock">
      <bool value="true"/>
    </param>`
to :
`    
    <param name="children_lock">
      <bool value="true" static="true"/>
    </param>`

**Comment by morevnaproject** [comment] 2019-03-23 13:06
Hi @maitreyi0505! I am afraid you are looking at wrong place. The files you referenced are Synfig's XML files - they contain artwork for icons. What you need to look is the code of Group Layer - https://github.com/synfig/synfig/blob/master/synfig-core/src/synfig/layers/layer_pastecanvas.cpp

I highly recommend to read Code Structure documentation - https://synfig-docs-dev.readthedocs.io/en/latest/common/structure.html ^__^

**Comment by yshkp** [comment] 2019-03-23 17:05
@morevnaproject Is it assigned to @maitreyi0505 ?

**Comment by morevnaproject** [comment] 2019-03-24 02:01
Yes. (Label fixed now ^__^).

**Comment by morevnaproject** [comment] 2019-05-18 11:09
Hi @maitreyi0505! Do you plan to continue working on this?

**Comment by ankit-kumar-dwivedi** [comment] 2019-07-28 06:26
@morevnaproject it's been 2 months and no response So I guess it is safe to un-assign this one [^_^]

**Comment by bajajvinamr** [comment] 2019-11-28 23:59
@ankit-kumar-dwivedi  I would like to work upon this

**Comment by ankit-kumar-dwivedi** [comment] 2019-11-29 17:48
@bajajvinamr sure you can start working.

**Comment by FirasH** [comment] 2020-03-16 16:21
There isn't any recent activity... Can I work on this one?

**Comment by FirasH** [comment] 2020-03-16 19:17
In the code there is already `set_static(true)` which should forbid animation by default, but still there is something missing...

https://github.com/synfig/synfig/blob/15ad054f18c37c0e36caca3c15b69d25ac51b04d/synfig-core/src/synfig/layers/layer_pastecanvas.cpp#L157-L161

**Comment by ice0** [comment] 2020-03-18 07:52
> There isn't any recent activity... Can I work on this one?

Sure.

> In the code there is already set_static(true) which should forbid animation by default, but still there is something missing...

Maybe this changed somewhere later.

**Comment by rodolforg** [comment] 2020-03-18 17:35
Following ice0's tip, @FirasH  Try to search in code
`git grep children_lock -- ':(exclude)*.sif'`

**Comment by FirasH** [comment] 2020-03-18 17:56
@rodolforg, I already tried that and probably the issue is deep somewhere (or I have it in front of me but I cannot see it)....

For this reason I made a test build where I added `.set_static(true)` to other parameters `ParamDesc` always in `layer_pastecanvas.cpp`, more specifically:
- `"origin"`
- `"time_dilation"`
- `"time_offset"`
- `"outline_grow"`

and to all of them the setting is applied correctly, except for `"children_lock"`.
I'm searching right now, but if you have some hints that would be very helpful :)

**Comment by rodolforg** [comment] 2020-03-18 18:40
Maybe `LayerParamTreeStore` or its parent class `CanvasTreeStore` handles it, as they're the data for parameter list tree view.

**Comment by FirasH** [comment] 2020-03-18 20:07
@rodolforg, I think the issue is found into `LayerEncapsulate`.

In fact if you create a group without any object (so that we avoid encapsulation/creation of a group) selecting `Layer > New Layer > Other > Group` it does correctly set `children_lock` to static.

**Comment by rodolforg** [comment] 2020-03-18 20:15
In this case, you could check layer dock and its toolbar actions in order
to figure it out if the "group " button callback is the guilty one

**Comment by FirasH** [comment] 2020-03-19 00:09
Basically what happens is that `LayerEncapsulate` (which is different from `Layer_PasteCanvas`) does not set the parameter `"children_lock"` to be static.

In the following code there is our issue:
https://github.com/synfig/synfig/blob/77164e8371269afb0490287f200f6c35fe067e88/synfig-studio/src/synfigapp/actions/layerencapsulate.cpp#L169

the newly created layer get its parameter for `"children_lock"` assigned to be `false`, but nothing is coded to set it to `static = true`.

@rodolforg, do you know which would be the best way to set it to static in this situation?

**Comment by rodolforg** [comment] 2020-03-19 00:32
Take a look in layer_encapsule in synfig core then. :)

**Comment by FirasH** [comment] 2020-03-19 10:56
@rodolforg created a merge request which contains the fix. What do you think about it?

**Closed** 2020-03-23 11:34 UTC
Labels: Easy, good first issue, help wanted
