### ISSUE TITLE
Cursor disappears in colors panel's eyedropper (Windows 10)

### ISSUE THREAD

**Issue by elthea** [synfig/synfig#536] opened 2018-04-27 10:45 UTC
**Synfig version & platform**: 1.3.6 & Windows 10
(we're more likely to help if you're using latest development builds)

**Issue description**: When I try to change color of an element using Colors panel/HSV/Eyedropper, what makes it very difficult to choose required color by mouse.

See attached movie.

[synfig-cut12.zip](https://github.com/synfig/synfig/files/1954784/synfig-cut12.zip)

**Comment by FadhilKwan** [comment] 2018-04-27 15:32
oh, this one is also related to mine! - #487  :D 
so i'll put just this here as well for more reference

by the way, you can use the eyedrop tool from toolbox, it works fine (no cursor disappearing)
also be mindful that it changes the outline color (pointed there) so make sure to swap the outline-region color first (the two-sided arrow icon)
![snip_20180427222714](https://user-images.githubusercontent.com/25135159/39371004-9a37e4dc-4a6a-11e8-9f33-9f11ab30250b.jpg)

**Comment by elthea** [comment] 2018-04-27 20:15
Thanks @FadhilKwan ! I'm closing my ticket.

**Comment by spikestheraccon** [comment] 2020-03-18 15:58
ver 1.3.13, windows 10. I have same issue. My cursor dissapear then i try to choose color with this button
![изображение](https://user-images.githubusercontent.com/56189267/76980162-af76e800-695a-11ea-8a68-4bfca8276416.png)

**Comment by rodolforg** [comment] 2020-03-20 13:31
Not reproducible in Debian Testing with gtkmm 3.24.2 .

**Comment by ice0** [comment] 2020-03-22 17:37
@rodolforg I think this is Windows only problem.

**Comment by rodolforg** [comment] 2020-03-22 17:39
Maybe a missing cursor image?

**Comment by ice0** [comment] 2020-03-23 08:23
@rodolforg I also thought about it. Can you check which one this can be? Maybe some Windows-related logic involved?

**Comment by rodolforg** [comment] 2020-03-24 17:52
https://github.com/GNOME/gtk/blob/aabdff2f3ef228344b983521ec68d2d0b2b89b02/gtk/deprecated/gtkcolorsel.c#L1707-L1708

So, it searches for color-picker cursor, but Adwaita icon theme doesn't have it.
Maybe we should update the deprecated GtkColorSelection to current GtkColorChooser editor widget.
In other words, we change this:
![Captura de tela de 2020-03-24 14-50-52](https://user-images.githubusercontent.com/1323987/77459760-f6dbf900-6dde-11ea-9370-e08f9ee50cb6.png)

to this:
![Captura de tela de 2020-03-24 14-49-33](https://user-images.githubusercontent.com/1323987/77459631-c4320080-6dde-11ea-9b5e-73a9e1903161.png)

**Comment by rodolforg** [comment] 2020-03-31 20:54
Regarding OP:
I tested and the problem is really the missing cursor file.
I copied and pasted the `cross-diamond.cur` and renamed to `color-picker.cur`.
It worked fine after I restarted the portable synfig 1.3.13 for Windows!

It's a Gtk issue (and Adwaita theme also), but it can be workaround'ed by release packaging :)
@ice0 @morevnaproject

**Comment by morevnaproject** [comment] 2020-04-18 14:17
Fixed in https://github.com/morevnaproject/morevna-builds/commit/9ef3a0c7d6a9de691fa8621d6291dfca708bc6f5. Waiting for rebuild. ^__^

**Comment by morevnaproject** [comment] 2020-04-18 17:05
Can anyone check if it is solved now? ^__^ - https://coolbug.org/downloads/morevna/builds/SynfigStudio-1.3.14-testing-2020.04.18-win64-596cd.zip

**Comment by rodolforg** [comment] 2020-04-19 03:11
Tested. It's fixed.
As well as #374

**Closed** 2020-04-19 08:14 UTC
Labels: Confirmed, Critical, Windows, help wanted
