### ISSUE TITLE
W10 stability is very frustrating

### ISSUE THREAD

**Issue by Blaggejoe** [synfig/synfig#467] opened 2017-12-03 20:29 UTC
**Synfig version & platform**:
S1.2.1 / W10 64bit / 1709

**Issue description**:
I started using Synfig some weeks ago with version 1.2.1 to do an short animation for my christmas - beamer lightshow. In the end the result was perfect but the way with Synfig was REALLY frustrating.
Some of the annoying behaviors i reported separatly in the last days. But the most catastrophic bug was the stability and crash-behavior on W10.
I would say, every 15 to 30 minutes Synfig crashed and with it the changes until the last saving. Unfortunatly am not able to reproduce the crash-behavior.
So my suggestion is:
1.
Implement a "crash-report-tool" that makes in case of a crash a short summary or dump some intersting files, that it can be sent easy to the developers.
2.
Make an "autosave on crash"-function, that saves the current project to some backup-path (for exampe "......../projectpath/crash-backup/xyz.sif". And inform the user about it. Inkscape for example does exactly this it in version 0.92.2.

But on these place a big "Thank you" to the developers!
Cheers
Blaggejoe

**Comment by keithnbrowncarlisle** [comment] 2018-04-12 16:00
I am so with you. I've reported a crash bug myself on windows 10, and intend to root out more.

if you can find some reproducable case, or simply list what you were attempting to do when it last crashed it may help @ice0 who seems to be actively tracking these down.

**Comment by morevnaproject** [comment] 2018-04-17 07:29
Yes, @ice0 is our new hired developer, who is in charge for resolving the stability issues. As announced here - https://morevnaproject.org/2018/02/27/new-developer-will-join-synfig-development-since-march-2018/

**Comment by Keyikedalube** [comment] 2021-07-13 08:23
Closing this in favor of #391

**Closed by Keyikedalube** 2021-07-13 08:23 UTC
