### ISSUE TITLE
"Remove Item (Smart)" crashes Synfig consistently

### ISSUE THREAD

**Issue by FirasH** [synfig/synfig#1102] opened 2020-01-21 23:14 UTC
**Synfig version & platform**:
Development version, revision e30f36

**Issue description**:
Steps:
0) Create a new synfig file
1) Add a new Skeleton: Layer > New Layer > Other > Skeleton
2) Create a Child Bone: right-click > Create Child Bone
3) Go to the Parameters panel and delete the child bone: right-click > Remove Item (Smart)

Synfig crashes consistently

**Comment by rodolforg** [comment] 2020-01-25 15:58
Obs: Step 3 should be actually "Go to the Parameters panel and delete the child bone: left-click to select child bone -> right-click > Remove Item (Smart)"
If you don't select it, it works fine.
(But the app still crashes on exit)

**Comment by morevnaproject** [comment] 2020-01-27 13:26
Is this a duplicate of #375?

**Comment by rodolforg** [comment] 2020-01-27 16:15
I don't know, but this specific issue is fixed by #1104 .

**Comment by FirasH** [comment] 2020-03-26 12:42
Fixed in `master` f806eb

**Closed** 2020-03-26 12:46 UTC
Labels: Confirmed, Crash
