### ISSUE TITLE
Cursor Highlight display and Selecting Folders  during screen recording URGENT

### ISSUE THREAD

**Issue by Khemardi** [synfig/synfig#2062] opened 2021-03-13 15:06 UTC
**Describe the bug**
Firstly: Whenever I'm recording a tutorial using the screen recorder and the cursor highlight is on, I can't open up layer groups or options that have a dropdown. I use a screen recorder called 'flashback" link here: https://www.flashbackrecorder.com/

Secondly: Whenever I change the default cursor image on windows, to one with a highlighted cursor; the highlight isn't displayed within Synfig itself, but if I hover over the start menu or the title bar, I'm able to see the highlighted cursor. Please note, this only happens with Synfig and no other application. I've also tried other screen recorders such as ShareX: https://getsharex.com/

This is a big issue because whenever I'm recording my tutorials I want the highlight on, so viewers can see where my mouse pointer is and what I'm clicking on. It also did not work on Synfig 1.2.

**To Reproduce**
1. Ues a screen recorder with the cursor highlight
2. While recording, open Synfig and move your mouse within the software. The cursor highlight will not display, but if it does, try creating a group layer and place some layers inside the folder, then try to open and close the Group layer or try to open a property with a dropdown option

**Expected behavior**
The cursor highlight should display while recording and allow me to open and close folders as well as dropdown properties.

**Screenshots**
Video of Issue: https://www.dropbox.com/s/w0yyft1r1s588l8/cursor_highlight_issue.mp4?dl=0
Screenshot of changing default windows cursor to a highlighted one: https://www.dropbox.com/s/suk48l0j8mafg2u/issue_other.png?dl=0

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS version: 10 Home
 - Synfig version: 1.4.0

**Additional context**

**Comment by rodolforg** [comment] 2021-03-13 15:36
Could you please try with a more recent Gtk?

**Comment by Khemardi** [comment] 2021-03-13 16:08
> Could you please try with a more recent Gtk?

I'm using the latest.

**Comment by rodolforg** [comment] 2021-03-13 20:33
You mean gtkmm >= 3.24.3 and gtk >= 3.24.25?

Can you test with Inkscape? it uses gtkmm too.

**Comment by Khemardi** [comment] 2021-03-13 22:28
Similar issue with inscape.

**Comment by rodolforg** [comment] 2021-03-14 02:16
So it's probably a gtk issue :/
I'll try with gimp later.

**Comment by rodolforg** [comment] 2021-03-14 18:17
Ok I didn't test it because flashback isn't free and it would pollute the machine I don't own. :(

Anyway, I think you can workaround it, for now, by selecting the group layer and pressing `+` (or `shift`+`right arrow`) to open the group or pressing `-` (or `shift`+`left arrow`) to close it.

**Comment by Khemardi** [comment] 2021-03-14 22:50
> Ok I didn't test it because flashback isn't free and it would pollute the machine I don't own. :(
> 
> Anyway, I think you can workaround it, for now, by selecting the group layer and pressing `+` (or `shift`+`right arrow`) key to open the group or pressing `-` (or `shift`+`left arrow`) to close it.

o.0 Wait.....how come I didn't know about those shortcuts? I tried it and it seems to work. You are a lifesaver!!!! This is indeed a good workaround. Thank you! :D

**Comment by BobSynfig** [comment] 2021-03-15 01:06
GTK support under Windows is not marvelous :/
Maybe you could try to
- deactivate hardware acceleration for the video
- modifiy the CSD parameter for Synfig

See https://gitlab.gnome.org/GNOME/gtk/-/issues/105
and https://bugs.launchpad.net/inkscape/+bug/1723247

**Comment by Khemardi** [comment] 2021-03-15 01:26
> GTK support under Windows is not marvelous :/
> Maybe you could try to
> 
> * deactivate hardware acceleration for the video
> * modifiy the CSD parameter for Synfig
> 
> See https://gitlab.gnome.org/GNOME/gtk/-/issues/105
> and https://bugs.launchpad.net/inkscape/+bug/1723247

So I see. I'll check out the links and thank you very much for the assistance.

**Comment by ice0** [comment] 2021-03-15 06:59
@Khemardi just checked with `flashbackrecorder`.
It works fine if you are using full screen recording and I have the same problem when using region recording. As a workaround, you can use full screen recording and crop the video afterwards.

**Comment by Khemardi** [comment] 2021-03-15 11:28
> @Khemardi just checked with `flashbackrecorder`.
> It works fine if you are using full screen recording and I have the same problem when using region recording. As a workaround, you can use full screen recording and crop the video afterwards.

This makes sense and it works. I've never entertained the thought that recording via region would be the problem as it works well with other apps. But it does make sense based on the framework. Anyway, I can record with the cursor highlight on again, so thank you both very much. So I would say this issue has been FIXED

**Comment by Keyikedalube** [comment] 2022-01-03 12:05
Closing this issue because other devs have mentioned above that this isn't caused by the Synfig program but the GUI library (GTK) it uses.

**Closed by Keyikedalube** 2022-01-03 12:05 UTC
Labels: Windows, reminder
