### ISSUE TITLE
Bug with control +z in windows

### ISSUE THREAD

**Issue by AlfredoArt** [synfig/synfig#355] opened 2017-04-29 05:57 UTC
**Synfig 1.3.2      windows 10**:

at the time that i press control + z for correct my error this version closes unexpectedly

**Comment by morevnaproject** [comment] 2017-05-03 10:48
Hello! Does this happens every time?

**Comment by AlfredoArt** [comment] 2017-05-06 04:53
yes, it does. Each twice control z
thanks for your answer

**Comment by morevnaproject** [comment] 2017-05-10 12:51
I cannot reproduce this. Can you please record a video showing how the problem happens?

**Comment by morevnaproject** [comment] 2017-05-10 12:52
Ah, wait... I did tested wrong version. Let me try again...

**Comment by morevnaproject** [comment] 2017-05-21 09:53
I am unable to reproduce this with Synfig 1.3.2 (32bit an 64bit). Can you please record a video of how this happens for you?

**Comment by ice0** [comment] 2018-05-23 14:22
Can't reproduce it too. So i close this, until bug is showed again :)

**Closed by ice0** 2018-05-23 14:22 UTC
